// This file is auto-generated by fetch_news.py — do not edit by hand
const NEWS_DATA = {
  "generated_at": "2026-08-21T15:04:28.644483+00:00",
  "generated_at_display": "21.08.2026 15:04",
  "summary": {
    "total": 80,
    "signal_total": 63,
    "macro_total": 17,
    "positive": 29,
    "negative": 14,
    "neutral": 20,
    "top_tickers": [
      {
        "ticker": "BTC",
        "count": 8
      },
      {
        "ticker": "SPY",
        "count": 4
      },
      {
        "ticker": "AAPL",
        "count": 3
      },
      {
        "ticker": "JPM",
        "count": 3
      },
      {
        "ticker": "UST10Y",
        "count": 2
      },
      {
        "ticker": "MRK",
        "count": 2
      }
    ],
    "sectors": [
      "Automotive / EV",
      "Banking & Finance",
      "Big Tech",
      "Bonds / Macro",
      "Consumer Goods",
      "Cryptocurrencies",
      "ETFs / Indices",
      "Healthcare",
      "Industrials",
      "Payments / Fintech",
      "Semiconductors",
      "Space"
    ],
    "source_counts": {
      "CNBC": 22,
      "Investing.com": 10,
      "Yahoo Finance": 15,
      "Nasdaq": 15,
      "MarketWatch": 5,
      "Mining.com": 2,
      "CoinDesk": 6,
      "Retail Dive": 1,
      "OilPrice.com": 4
    }
  },
  "indices": [
    {
      "name": "S&P 500",
      "symbol": "^GSPC",
      "unit": "index",
      "price": 7680.09,
      "change_abs": -105.67,
      "change_pct": -1.36,
      "spark": [
        7673.9102,
        7666.0698,
        7663.2002,
        7664.0,
        7653.9702,
        7654.02,
        7653.73,
        7650.9902,
        7653.7998,
        7653.23,
        7649.48,
        7642.21,
        7670.21,
        7664.2402,
        7665.6401,
        7665.1001,
        7664.7998,
        7676.6899,
        7679.8599,
        7680.0898
      ]
    },
    {
      "name": "Dow Jones",
      "symbol": "^DJI",
      "unit": "index",
      "price": 53181.92,
      "change_abs": -550.49,
      "change_pct": -1.02,
      "spark": [
        53011.1211,
        52955.0117,
        52910.6484,
        52907.2109,
        52849.3906,
        52839.0312,
        52836.3086,
        52806.1797,
        52832.6992,
        52818.0508,
        52803.0312,
        52773.7383,
        53121.7305,
        53073.8906,
        53139.7305,
        53133.5117,
        53087.6094,
        53164.1016,
        53184.0117,
        53181.9219
      ]
    },
    {
      "name": "Nasdaq Composite",
      "symbol": "^IXIC",
      "unit": "index",
      "price": 26170.85,
      "change_abs": -558.31,
      "change_pct": -2.09,
      "spark": [
        26114.7012,
        26083.7949,
        26086.0898,
        26094.0293,
        26040.4941,
        26052.4297,
        26050.2949,
        26054.6035,
        26075.1855,
        26088.2773,
        26081.1172,
        26062.4844,
        26106.1484,
        26107.1562,
        26083.0254,
        26090.8086,
        26098.0762,
        26145.8145,
        26167.9219,
        26170.8555
      ]
    },
    {
      "name": "Russell 2000",
      "symbol": "^RUT",
      "unit": "index",
      "price": 3003.41,
      "change_abs": -65.01,
      "change_pct": -2.12,
      "spark": [
        2998.8364,
        2994.0403,
        2992.1494,
        2992.4309,
        2994.3857,
        2990.6406,
        2992.9417,
        2990.2512,
        2990.3599,
        2993.4341,
        2993.7981,
        2992.5781,
        2992.03,
        3013.6323,
        3013.0991,
        3006.5759,
        3006.2708,
        3001.3936,
        3002.864,
        3003.4055
      ]
    },
    {
      "name": "FTSE 100 (UK)",
      "symbol": "^FTSE",
      "unit": "index",
      "price": 10817.48,
      "change_abs": 67.38,
      "change_pct": 0.63,
      "spark": [
        10753.2998,
        10750.5996,
        10759.3398,
        10763.75,
        10768.6396,
        10763.75,
        10761.9697,
        10772.25,
        10771.4902,
        10779.5,
        10775.1904,
        10781.5498,
        10799.4697,
        10815.8604,
        10821.5098,
        10824.6797,
        10828.8398,
        10821.0898,
        10817.4199,
        10817.4805
      ]
    },
    {
      "name": "DAX (Germany)",
      "symbol": "^GDAXI",
      "unit": "index",
      "price": 26149.87,
      "change_abs": -290.44,
      "change_pct": -1.1,
      "spark": [
        26021.7109,
        26016.1895,
        26020.9805,
        26048.4297,
        26061.1309,
        26047.9102,
        26050.1504,
        26060.7109,
        26070.0508,
        26090.9199,
        26088.9902,
        26105.4609,
        26114.2402,
        26117.6504,
        26147.2891,
        26123.5391,
        26147.4492,
        26148.9707,
        26150.5293,
        26149.8691
      ]
    },
    {
      "name": "Euro Stoxx 50",
      "symbol": "^STOXX50E",
      "unit": "index",
      "price": 6463.24,
      "change_abs": -67.21,
      "change_pct": -1.03,
      "spark": [
        6436.1699,
        6433.1499,
        6436.0098,
        6438.4902,
        6442.8101,
        6438.79,
        6440.0898,
        6445.1699,
        6446.9902,
        6452.4399,
        6449.4502,
        6452.4702,
        6453.54,
        6452.2202,
        6460.9502,
        6454.9502,
        6464.77,
        6464.6899,
        6463.4102,
        6463.2402
      ]
    },
    {
      "name": "Nikkei 225 (Japan)",
      "symbol": "^N225",
      "unit": "index",
      "price": 66016.36,
      "change_abs": -3203.89,
      "change_pct": -4.63,
      "spark": [
        65495.0195,
        65644.5078,
        65801.0,
        65734.9688,
        65919.7969,
        66019.4531,
        66008.4531,
        65951.1094,
        65924.3828,
        66002.2812,
        65916.2891,
        65963.5,
        65991.5234,
        65973.1797,
        65888.8906,
        65816.2031,
        65868.1484,
        65896.6875,
        66033.5391,
        66016.3594
      ]
    },
    {
      "name": "Hang Seng (Hong Kong)",
      "symbol": "^HSI",
      "unit": "index",
      "price": 26009.46,
      "change_abs": 892.61,
      "change_pct": 3.55,
      "spark": [
        25832.1094,
        25879.0,
        25864.6797,
        25867.7207,
        25887.6191,
        25886.5391,
        25883.2402,
        25882.3008,
        25895.9297,
        25898.0996,
        25899.9297,
        25915.8594,
        25962.1797,
        25965.6309,
        25955.9395,
        25971.3301,
        25951.3398,
        25974.8398,
        25994.4199,
        26009.4609
      ]
    },
    {
      "name": "Gold (futures)",
      "symbol": "GC=F",
      "unit": "index",
      "price": 4647.4,
      "change_abs": 229.6,
      "change_pct": 5.2,
      "spark": [
        4645.6001,
        4650.3999,
        4645.7998,
        4647.5,
        4655.7002,
        4654.2998,
        4654.1001,
        4650.0,
        4642.2002,
        4630.5,
        4634.7002,
        4642.0,
        4640.8999,
        4644.8999,
        4638.2998,
        4646.2998,
        4659.5,
        4639.0,
        4646.5,
        4647.3999
      ]
    },
    {
      "name": "WTI Crude Oil (futures)",
      "symbol": "CL=F",
      "unit": "index",
      "price": 86.63,
      "change_abs": 2.13,
      "change_pct": 2.52,
      "spark": [
        86.61,
        86.82,
        87.05,
        87.22,
        86.43,
        86.47,
        86.96,
        87.13,
        87.03,
        86.81,
        86.87,
        86.79,
        86.91,
        86.76,
        86.46,
        86.6,
        86.42,
        86.41,
        86.58,
        86.63
      ]
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC-USD",
      "unit": "index",
      "price": 77542.28,
      "change_abs": 13036.03,
      "change_pct": 20.21,
      "spark": [
        77829.0,
        77802.3594,
        77520.4688,
        77386.0078,
        76854.5,
        76709.6172,
        76901.3203,
        76667.9297,
        77409.9062,
        77195.1484,
        77168.3984,
        77067.9609,
        77283.3906,
        77244.2266,
        76759.0938,
        77043.3828,
        77110.5,
        77374.7812,
        77432.8125,
        77542.2812
      ]
    },
    {
      "name": "10-Year US Treasury Yield",
      "symbol": "^TNX",
      "unit": "yield_pct",
      "price": 0.47,
      "change_abs": 0.0,
      "change_pct": 0.04,
      "spark": [
        0.4698,
        0.47,
        0.4704,
        0.4704,
        0.4696,
        0.47,
        0.4698,
        0.47,
        0.4696,
        0.4696,
        0.4696,
        0.4704,
        0.4712,
        0.472,
        0.4716,
        0.4714,
        0.472,
        0.4732,
        0.4726,
        0.4726
      ]
    },
    {
      "name": "VIX (Fear Index)",
      "symbol": "^VIX",
      "unit": "index",
      "price": 15.35,
      "change_abs": 0.16,
      "change_pct": 1.05,
      "spark": [
        15.7,
        15.69,
        15.67,
        15.67,
        15.49,
        15.45,
        15.46,
        15.5,
        15.43,
        15.41,
        15.42,
        15.49,
        15.48,
        15.47,
        15.49,
        15.44,
        15.42,
        15.41,
        15.35,
        15.35
      ]
    }
  ],
  "items": [
    {
      "title": "Ken Griffin says Citadel unwound more than 80% of risk tied to Situational Awareness portfolio",
      "link": "https://www.cnbc.com/2026/08/21/citadel-situational-awareness-ken-griffin.html",
      "description": "",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T15:01:19+00:00",
      "published_display": "21.08 15:01",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump to allow import of 300,000 metric tons of ground beef without tariff",
      "link": "https://www.cnbc.com/2026/08/21/trump-ground-beef-import-tariff.html",
      "description": "Beef prices in the U.S have soared in 2026 due to a reduction in the nation's cattle herd.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:58:56+00:00",
      "published_display": "21.08 14:58",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump tariff deadline looms as U.S. and Canada say final trade deal is near",
      "link": "https://www.cnbc.com/2026/08/21/trump-canada-tariffs-trade-deal-deadline.html",
      "description": "Businesses have warned that Trump's new 50% duties could cripple their U.S. sales if they take effect.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:53:47+00:00",
      "published_display": "21.08 14:53",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Boston Beer stock falls as CFO Reynoso to depart",
      "link": "https://www.investing.com/news/stock-market-news/boston-beer-stock-falls-as-cfo-reynoso-to-depart-93CH-4871871",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEB6U08A_M.jpg",
      "published": "2026-08-21T14:52:25",
      "published_display": "21.08 14:52",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "S&P 500 rebounds after sell-off but remains on pace for weekly decline: Live updates",
      "link": "https://www.cnbc.com/2026/08/20/stock-market-today-live-updates.html",
      "description": "Stocks rose on Friday as investors tried to find their footing following a steep sell-off driven by rising Treasury yields.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:50:13+00:00",
      "published_display": "21.08 14:50",
      "sentiment": "positive",
      "tickers": [
        "UST10Y",
        "SPY"
      ],
      "sectors": [
        "Bonds / Macro",
        "ETFs / Indices"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Greece stocks higher at close of trade; Athens General Composite up 1.34%",
      "link": "https://www.investing.com/news/stock-market-news/greece-stocks-higher-at-close-of-trade-athens-general-composite-up-134-4871870",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEB5B0SL_M.jpg",
      "published": "2026-08-21T14:50:05",
      "published_display": "21.08 14:50",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Apple paid 40% of its global taxes to Ireland in last fiscal year",
      "link": "https://finance.yahoo.com/economy/policy/articles/apple-paid-40-global-taxes-144940102.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/reuters-finance.com/521d04c6f112b7eb4d5a8ad14df80874.jpg",
      "published": "2026-08-21T14:49:40+00:00",
      "published_display": "21.08 14:49",
      "sentiment": "neutral",
      "tickers": [
        "AAPL"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why is Cleveland-Cliffs stock surging today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-clevelandcliffs-stock-surging-today-93CH-4871869",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEB59082_M.jpg",
      "published": "2026-08-21T14:49:25",
      "published_display": "21.08 14:49",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Merck stock analysis: great pipeline at a stretched valuation",
      "link": "https://www.investing.com/news/stock-market-news/merck-stock-analysis-great-pipeline-at-a-stretched-valuation-93CH-4871868",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC7309G_M.jpg",
      "published": "2026-08-21T14:47:46",
      "published_display": "21.08 14:47",
      "sentiment": "neutral",
      "tickers": [
        "MRK"
      ],
      "sectors": [
        "Healthcare"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "$32 million: The number incoming Apple CEO John Ternus has to beat to measure up to Tim Cook",
      "link": "https://finance.yahoo.com/technology/article/32-million-the-number-incoming-apple-ceo-john-ternus-has-to-beat-to-measure-up-to-tim-cook-144626360.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/Q0kUhiEky2jFke6pfsQeEg--~B/aD0yMjg2O3c9MzQyOTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-08/2214e4d4-5ef0-4c26-b7b9-bd7a9e8cd6fc",
      "published": "2026-08-21T14:46:26+00:00",
      "published_display": "21.08 14:46",
      "sentiment": "neutral",
      "tickers": [
        "AAPL"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "4 memory stocks are darlings of the AI boom. How they differ and why we own Micron",
      "link": "https://www.cnbc.com/2026/08/21/4-memory-stocks-are-darlings-of-the-ai-boom-how-they-differ-and-why-we-own-micron.html",
      "description": "While often trading together, these companies are not the same.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:44:02+00:00",
      "published_display": "21.08 14:44",
      "sentiment": "positive",
      "tickers": [
        "MU"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Star Equity (STRR) Q2 2026 Earnings Call Transcript",
      "link": "https://finance.yahoo.com/markets/stocks/articles/star-equity-strr-q2-2026-144251956.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/e48e86dda35543079ee2080fd9208b73.png",
      "published": "2026-08-21T14:42:51+00:00",
      "published_display": "21.08 14:42",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Florida real estate mogul says your home is ‘a terrible investment’ — and he’d put $100K somewhere else. Is he right?",
      "link": "https://finance.yahoo.com/real-estate/articles/florida-real-estate-mogul-says-144000147.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/moneywise_327/d7e7aa99afd662040316a45f6111de38.jpg",
      "published": "2026-08-21T14:40:00+00:00",
      "published_display": "21.08 14:40",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Goldman Sachs and Alibaba among market cap stock movers on Friday",
      "link": "https://www.investing.com/news/stock-market-news/goldman-sachs-and-alibaba-among-market-cap-stock-movers-on-friday-93CH-4871858",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEHAF0OJ-ORUBS_L.jpg",
      "published": "2026-08-21T14:37:24",
      "published_display": "21.08 14:37",
      "sentiment": "positive",
      "tickers": [
        "BABA",
        "GS"
      ],
      "sectors": [
        "Banking & Finance",
        "Big Tech"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "How a 76-Year-Old Collects $5,600 a Month From Just Two Funds: JEPQ and VYM",
      "link": "https://finance.yahoo.com/markets/stocks/articles/76-old-collects-5-600-143642768.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/d8bb12829fe74553ece940e4658d3204.jpg",
      "published": "2026-08-21T14:36:42+00:00",
      "published_display": "21.08 14:36",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Looking to Generate Passive Income From Stocks? 3 Magnificent High-Yield Dividend Stocks to Buy Now",
      "link": "https://finance.yahoo.com/markets/stocks/articles/looking-generate-passive-income-stocks-143500552.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/0c57ad1d033b848f2cf90cd6c6373644.jpg",
      "published": "2026-08-21T14:35:00+00:00",
      "published_display": "21.08 14:35",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Volkswagen CEO says overhead costs exceed rivals by over 30%",
      "link": "https://www.investing.com/news/stock-market-news/volkswagen-ceo-says-overhead-costs-exceed-rivals-by-over-30-93CH-4871854",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPECBK07G_M.jpg",
      "published": "2026-08-21T14:34:15",
      "published_display": "21.08 14:34",
      "sentiment": "negative",
      "tickers": [
        "VOW3"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why is Merck stock surging to a 52-week high today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-merck-stock-surging-to-a-52week-high-today-93CH-4871851",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC0Q0MJ_M.jpg",
      "published": "2026-08-21T14:33:36",
      "published_display": "21.08 14:33",
      "sentiment": "positive",
      "tickers": [
        "MRK"
      ],
      "sectors": [
        "Healthcare"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Corn Slipping Back on Friday Morning",
      "link": "https://www.nasdaq.com/articles/corn-slipping-back-friday-morning-0",
      "description": "Corn prices are 1 to 2 cents lower so far on Friday morning. Futures closed the Thursday session holding onto most of the intraday gains, up 1 to 5 ¾ cents across the front months. Open interest was down 23,012 contracts on Thursday,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:32:54+00:00",
      "published_display": "21.08 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Wheat Falling Back to Start Friday Trade",
      "link": "https://www.nasdaq.com/articles/wheat-falling-back-start-friday-trade",
      "description": "Wheat is showing losses of 3 to 8 cents on Friday morning. The wheat complex posted mixed action across the three exchanges on Thursday. Chicago SRW contracts were fractionally to 2 ½ cents higher on the day. KC HRW futures closed the…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:32:54+00:00",
      "published_display": "21.08 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin on track for 23% weekly gain as investor optimism floods back",
      "link": "https://www.cnbc.com/2026/08/21/bitcoin-gain-cryptocurrency-investors-optimistic.html",
      "description": "The flagship digital currency has enjoyed a strong week boosted by several contributing factors.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:32:08+00:00",
      "published_display": "21.08 14:32",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 50.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stock Market Today: Dow Bounces After Sell-Off; Bitcoin Jumps Near $77K, Ross Pops On Outlook (Live Coverage)",
      "link": "https://www.investors.com/market-trend/stock-market-today/dow-jones-sp500-nasdaq-stock-market-sell-off-bitcoin-surges/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/55ca4252bd7c66820fc61ce444908e68.jpg",
      "published": "2026-08-21T14:32:04+00:00",
      "published_display": "21.08 14:32",
      "sentiment": "neutral",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stock Market Rally Buckles; Moderna, Gold, Bitcoin Surge While Walmart Tumbles: Weekly Review",
      "link": "https://www.investors.com/news/stock-market-rally-buckles-moderna-gold-bitcoin-surge-walmart-tumbles/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/63d92fcd01ffb99464c6745e212b7302.jpg",
      "published": "2026-08-21T14:31:51+00:00",
      "published_display": "21.08 14:31",
      "sentiment": "positive",
      "tickers": [
        "WMT",
        "MRNA",
        "BTC"
      ],
      "sectors": [
        "Consumer Goods",
        "Cryptocurrencies",
        "Healthcare"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Apollo Global reveals data breach after hackers target financial firms",
      "link": "https://www.investing.com/news/stock-market-news/apollo-global-confirms-data-breach-after-hackers-target-financial-firms-4871835",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM7K0YB_L.jpg",
      "published": "2026-08-21T14:31:31",
      "published_display": "21.08 14:31",
      "sentiment": "negative",
      "tickers": [
        "TGT"
      ],
      "sectors": [
        "Consumer Goods"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nasdaq 100 Movers: SPCX, HONIV",
      "link": "https://www.nasdaq.com/articles/nasdaq-100-movers-spcx-honiv",
      "description": "In early trading on Friday, shares of Honeywell International topped the list of the day's best performing components of the Nasdaq 100 index, trading up 7.5%. Year to date, Honeywell International registers a 42.2% gain. And the worst…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:31:20+00:00",
      "published_display": "21.08 14:31",
      "sentiment": "positive",
      "tickers": [
        "SPCX",
        "HON",
        "QQQ"
      ],
      "sectors": [
        "ETFs / Indices",
        "Industrials",
        "Space"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "This Stock Could Be a Major AI Winner Through 2027. What’s It Worth?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/stock-could-major-ai-winner-143032093.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/973e826dbc761c4e09780d018d7d9dc6.jpg",
      "published": "2026-08-21T14:30:32+00:00",
      "published_display": "21.08 14:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "JD.com offers concessions in EU probe of Ceconomy takeover bid",
      "link": "https://finance.yahoo.com/markets/stocks/articles/jd-com-offers-concessions-eu-143022912.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/retail_insight_network_724/8ee723f19fb823a3a767fa1716d2da8d.jpg",
      "published": "2026-08-21T14:30:22+00:00",
      "published_display": "21.08 14:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hogs Look to Round Out the Week",
      "link": "https://www.nasdaq.com/articles/hogs-look-round-out-week-1",
      "description": "Lean hog futures saw losses of 25 cents to $1.27 in the front months on Thursday, with the deferreds mixed. USDA’s national base hog price was reported at $92.34 in the Thursday PM report, up 24 cents from the day prior. The CME Lean…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:28:43+00:00",
      "published_display": "21.08 14:28",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cattle Look to Friday Trade as President Trump Lifts Import Tariffs for 90 Days",
      "link": "https://www.nasdaq.com/articles/cattle-look-friday-trade-president-trump-lifts-import-tariffs-90-days",
      "description": "Live cattle futures posted gains of 77 cents to $1.125 at the Thursday close, with August 7 cents lower. Open interest suggested modest new buying, up 3,076 contracts. Cash trade has picked up a few at $355-360 dressed and $226. The…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:28:43+00:00",
      "published_display": "21.08 14:28",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks Settle Lower as Rising Crude Prices Spur Inflation Fears",
      "link": "https://www.nasdaq.com/articles/stocks-settle-lower-rising-crude-prices-spur-inflation-fears",
      "description": "The S&P 500 Index ($SPX ) (SPY ) closed down by -0.87% on Thursday, the Dow Jones Industrial Average ($DOWI ) (DIA ) closed down by -1.32%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) closed down by -0.72%. E-mini S&P futures (ESU26 ) fell…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:28:43+00:00",
      "published_display": "21.08 14:28",
      "sentiment": "negative",
      "tickers": [
        "SPY",
        "QQQ",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bernstein remains bullish on SpaceX but sees challenges in telecom ambitions",
      "link": "https://www.investing.com/news/stock-market-news/bernstein-remains-bullish-on-spacex-but-sees-challenges-in-telecom-ambitions-4871848",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEM6M02C_L.jpg",
      "published": "2026-08-21T14:27:53",
      "published_display": "21.08 14:27",
      "sentiment": "neutral",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "S&P 500 Movers: WAT, HOOD",
      "link": "https://www.nasdaq.com/articles/sp-500-movers-wat-hood",
      "description": "In early trading on Friday, shares of Robinhood Markets topped the list of the day's best performing components of the S&P 500 index, trading up 9.7%. Year to date, Robinhood Markets has lost about 7.8% of its value. And the worst…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:27:08+00:00",
      "published_display": "21.08 14:27",
      "sentiment": "positive",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cotton Back to Rallying Early on Friday",
      "link": "https://www.nasdaq.com/articles/cotton-back-rallying-early-friday",
      "description": "Cotton price action is up 40 to 65 points so far on Friday. Futures posted marginally mixed trade on Thursday, with contracts down 10 points to 44 points higher. Crude oil was up $2.32 with the US dollar index $0.054 higher. Export…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:26:31+00:00",
      "published_display": "21.08 14:26",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Soybeans Facing Modest Pressure on Friday Morning",
      "link": "https://www.nasdaq.com/articles/soybeans-facing-modest-pressure-friday-morning",
      "description": "Soybeans are trading with Friday morning losses of 3 to 4 cents. Futures closed the Thursday session mixed, with contracts down 1 ½ to 2 ½ cents lower across the board. Open interest slipped 4,638 contracts on Thursday. September…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:26:31+00:00",
      "published_display": "21.08 14:26",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "USA Rare Earth Rises 8%, Critical Metals Jumps 10%, MP Materials Climbs 5% as the Resource Sector Catches a Bid",
      "link": "https://finance.yahoo.com/markets/commodities/articles/usa-rare-earth-rises-8-142609271.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/696d429890580ffca2e75810a743870c.jpg",
      "published": "2026-08-21T14:26:09+00:00",
      "published_display": "21.08 14:26",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "WIA Ex-Dividend Reminder - 8/24/26",
      "link": "https://www.nasdaq.com/articles/wia-ex-dividend-reminder-8-24-26",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 8/24/26, Western Asset/Claymore Inflation-Linked Securities & Income Fund (Symbol: WIA) will trade ex-dividend, for its monthly dividend of $0.052, payable on 8/31/26.…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:22:15+00:00",
      "published_display": "21.08 14:22",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Flaherty & Crumrine Preferred Securities Income Fund Incorporated About To Put More Money In Your Pocket (FFC)",
      "link": "https://www.nasdaq.com/articles/flaherty-crumrine-preferred-securities-income-fund-incorporated-about-put-more-money-your",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 8/24/26, Flaherty & Crumrine Preferred Securities Income Fund Incorporated (Symbol: FFC) will trade ex-dividend, for its monthly dividend of $0.1046, payable on 8/31/26.…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:22:11+00:00",
      "published_display": "21.08 14:22",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cash Dividend On The Way From Pan American Silver (PAAS)",
      "link": "https://www.nasdaq.com/articles/cash-dividend-way-pan-american-silver-paas",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 8/24/26, Pan American Silver Corp (Symbol: PAAS) will trade ex-dividend, for its quarterly dividend of $0.184, payable on 9/4/26. As a percentage of PAAS's recent stock…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:22:07+00:00",
      "published_display": "21.08 14:22",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dow Movers: AAPL, HONIV",
      "link": "https://www.nasdaq.com/articles/dow-movers-aapl-honiv-0",
      "description": "In early trading on Friday, shares of Honeywell International topped the list of the day's best performing Dow Jones Industrial Average components, trading up 7.5%. Year to date, Honeywell International registers a 42.2% gain. And the…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:21:59+00:00",
      "published_display": "21.08 14:21",
      "sentiment": "positive",
      "tickers": [
        "AAPL",
        "HON",
        "DJI"
      ],
      "sectors": [
        "Big Tech",
        "ETFs / Indices",
        "Industrials"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cash Dividend On The Way From Templeton Emerging Markets Income Fund (TEI)",
      "link": "https://www.nasdaq.com/articles/cash-dividend-way-templeton-emerging-markets-income-fund-tei",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 8/24/26, Templeton Emerging Markets Income Fund (Symbol: TEI) will trade ex-dividend, for its monthly dividend of $0.054, payable on 8/31/26. As a percentage of TEI's…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:20:28+00:00",
      "published_display": "21.08 14:20",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Ryder System About To Put More Money In Your Pocket (R)",
      "link": "https://www.nasdaq.com/articles/ryder-system-about-put-more-money-your-pocket-r",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 8/24/26, Ryder System, Inc. (Symbol: R) will trade ex-dividend, for its quarterly dividend of $1.01, payable on 9/18/26. As a percentage of R's recent stock price of…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-21T14:19:08+00:00",
      "published_display": "21.08 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "S&P 500 rejects highs, tests 7,650 support: Hourly levels",
      "link": "https://www.investing.com/news/stock-market-news/sp-500-coils-near-7794-ahead-of-breakout-live-levels-93CH-4863478",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/SP500StandardandPoors500Index_800x533_L_1657544297.jpg",
      "published": "2026-08-21T14:18:00",
      "published_display": "21.08 14:18",
      "sentiment": "neutral",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Crypto Miner Poolin Files For Bankruptcy",
      "link": "https://finance.yahoo.com/markets/crypto/articles/crypto-miner-poolin-files-bankruptcy-141500892.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/cryptoprowl_304/12015d29e523ee8eac8589ca39c41884.jpg",
      "published": "2026-08-21T14:15:00+00:00",
      "published_display": "21.08 14:15",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Indiana family discovers $100K in hidden damage after buying $200K home — Ramsey hosts weigh the $30K gamble to sue",
      "link": "https://finance.yahoo.com/real-estate/articles/indiana-family-discovers-100k-hidden-141500156.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/moneywise_327/85f4c52ccfb059f2ecb8c4e64b8c85b2.jpg",
      "published": "2026-08-21T14:15:00+00:00",
      "published_display": "21.08 14:15",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Dollar near three-month low on Treasury buyback worries",
      "link": "https://finance.yahoo.com/markets/currencies/articles/dollar-falls-as-investors-weigh-us-treasurys-rescue-efforts-053406923.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/reuters.com/fa378fb3d0727afeafec81852f138047.jpg",
      "published": "2026-08-21T14:10:57+00:00",
      "published_display": "21.08 14:10",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump admin taps former JPMorgan Chase exec Matt Zames to advise Social Security agency",
      "link": "https://www.cnbc.com/2026/08/21/jpmorgan-matt-zames-social-security-administration.html",
      "description": "Matt Zames is taking an unpaid position to help his former JPMorgan colleague Frank Bisignano tackle modernization of the SSA, CNBC has learned.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:06:15+00:00",
      "published_display": "21.08 14:06",
      "sentiment": "neutral",
      "tickers": [
        "JPM"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Social Security union says it needs $3 billion and another 20,000 workers to fix long wait times and ‘ghost offices’",
      "link": "https://www.marketwatch.com/story/ghost-offices-and-long-wait-times-social-security-workers-demand-3-billion-and-20-000-hires-ac975af0?mod=mw_rss_topstories",
      "description": "“The public is going to have a harder and harder time accessing these benefits,” union official said.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-52854289",
      "published": "2026-08-21T14:03:00+00:00",
      "published_display": "21.08 14:03",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "How one Silicon Valley firm is seizing an opportunity from Premier League soccer's gambling ad clampdown",
      "link": "https://www.cnbc.com/2026/08/21/premier-league-gambling-shirt-sponsors.html",
      "description": "Premier League clubs have removed betting brands from shirt fronts, opening new sponsorship opportunities while bookmakers shift spending elsewhere.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T14:00:02+00:00",
      "published_display": "21.08 14:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "U.S. military says it aided passage of 660 million barrels of oil through Strait of Hormuz since May",
      "link": "https://www.cnbc.com/2026/08/21/strait-hormuz-central-command-centcom-oil-iran-war.html",
      "description": "The security situation in Hormuz remains contested but the U.S. is helping oil get through the strait.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:55:15+00:00",
      "published_display": "21.08 13:55",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "International student enrollment falls amid tighter U.S. visa policies, reports show",
      "link": "https://www.cnbc.com/2026/08/21/international-student-enrollment-us-visa-policies.html",
      "description": "Amid changes to student visa policies, colleges and universities are likely to see fewer international students enrolled this fall, reports show.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:46:01+00:00",
      "published_display": "21.08 13:46",
      "sentiment": "negative",
      "tickers": [
        "V"
      ],
      "sectors": [
        "Payments / Fintech"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Most Americans aren't anti-vaccine. They're uncertain — and that's a growing public health challenge",
      "link": "https://www.cnbc.com/2026/08/21/why-vaccination-rates-are-falling-in-the-us.html",
      "description": "The bigger issue at hand may be that many Americans fall into a large, uncertain middle ground – neither firmly pro-vaccine nor staunchly opposed.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:45:26+00:00",
      "published_display": "21.08 13:45",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "JPMorgan is worried about an autumn downturn. Says AI stocks show similarities to 2000 tech peak",
      "link": "https://www.cnbc.com/2026/08/21/jpmorgan-worries-about-autumn-downturn-in-stocks.html",
      "description": "Stocks are headed for a weekly decline, and JPMorgan thinks there could be further downside ahead.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:34:59+00:00",
      "published_display": "21.08 13:34",
      "sentiment": "negative",
      "tickers": [
        "JPM"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nvidia earnings could rescue a stalled-out stock market — if the AI chip maker breaks this trend",
      "link": "https://www.marketwatch.com/story/nvidia-earnings-could-rescue-a-stalling-stock-market-if-the-ai-chip-maker-breaks-this-trend-9b6504bc?mod=mw_rss_topstories",
      "description": "Shares of Jensen Huang’s company have struggled to make headway since its previous results day.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-86072454",
      "published": "2026-08-21T13:33:00+00:00",
      "published_display": "21.08 13:33",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Gold rebounds as bond jitters, debt fears and weaker dollar revive bullion demand",
      "link": "https://www.cnbc.com/2026/08/21/gold-prices-us-debt-dollar.html",
      "description": "Gold is rebounding as investors weigh U.S. debt concerns, a weaker dollar and stubbornly high Treasury yields.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:21:19+00:00",
      "published_display": "21.08 13:21",
      "sentiment": "positive",
      "tickers": [
        "UST10Y"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The Los Angeles Lakers sold for $12.5 billion. Here’s what every NBA team is now worth",
      "link": "https://www.cnbc.com/2026/08/20/heres-how-the-los-angeles-lakers-12point5b-sale-impacts-the-value-of-all-30-nba-teams.html",
      "description": "The pending $12.5 billion Lakers sale would lift CNBC’s average NBA team valuation 21% to $6.68 billion, with the Warriors still No. 1.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:15:27+00:00",
      "published_display": "21.08 13:15",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bessent says there's a 'very good chance' U.S. budget deficit under Trump has peaked",
      "link": "https://www.cnbc.com/2026/08/20/bessent-budget-deficit-trump.html",
      "description": "Treasury Secretary Scott Bessent said Thursday that there's a \"very good chance\" of the U.S. has seen its budget deficit peak under President Donald Trump.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:11:41+00:00",
      "published_display": "21.08 13:11",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Wall Street's existential crisis over perpetual futures — the 24/7 security on steroids — just got urgent",
      "link": "https://www.cnbc.com/2026/08/21/wall-streets-existential-crisis-over-perpetual-futures-the-24/7-security-on-steroids-just-got-urgent.html",
      "description": "Perpetual futures, or perps, are shaking up exchanges as investors seek continuous access to trading.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T13:04:19+00:00",
      "published_display": "21.08 13:04",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin on track for best week in more than two years. Can this mean the next crypto bull market has arrived?",
      "link": "https://www.marketwatch.com/story/bitcoin-on-track-for-best-week-in-more-than-two-years-has-the-next-crypto-bull-market-arrived-0181180c?mod=mw_rss_topstories",
      "description": "Is bitcoin ready to move on after a lengthy slump? One analyst says investors should be careful in trying to guess a bottom for the crypto.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-97523838",
      "published": "2026-08-21T13:01:00+00:00",
      "published_display": "21.08 13:01",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bessent's efforts in the Treasury market so far haven't worked. Here's what else he can try",
      "link": "https://www.cnbc.com/2026/08/20/bessents-efforts-in-the-treasury-market-so-far-havent-worked-heres-what-else-he-can-try.html",
      "description": "Market experts showed skepticism at whether the push would succeed against a bevy of factors working against Treasurys.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T12:43:04+00:00",
      "published_display": "21.08 12:43",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Walmart just had its worst day in 4 years. JPMorgan says buy it now",
      "link": "https://www.cnbc.com/2026/08/21/walmart-just-had-its-worst-day-in-4-years-jpmorgan-says-buy-it-now.html",
      "description": "Walmart shares are cheaper than usual following the stock's steep decline on Thursday after its earnings report, according to JPMorgan.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T12:17:51+00:00",
      "published_display": "21.08 12:17",
      "sentiment": "positive",
      "tickers": [
        "WMT",
        "JPM"
      ],
      "sectors": [
        "Banking & Finance",
        "Consumer Goods"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "When it comes to stock buybacks, anything SK Hynix can do, Samsung can do bigger",
      "link": "https://www.marketwatch.com/story/when-it-comes-to-returning-cash-to-shareholders-anything-sk-hynix-can-do-samsung-can-do-bigger-87db6ef4?mod=mw_rss_topstories",
      "description": "As demand far outstrips supply in the memory-chip market, SK Hynix and Samsung Electronics are generating outsize profits and throwing off huge free cash flow. Now both companies plan to return lots of this to shareholders",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-09424984",
      "published": "2026-08-21T12:15:00+00:00",
      "published_display": "21.08 12:15",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bunker Hill to buy Silver47 in $163M all-stock deal",
      "link": "https://www.mining.com/bunker-hill-to-buy-silver47-in-163m-all-stock-deal/",
      "description": "Bunker Hill adds Silver47's exploration portfolio in Alaska, Nevada, and New Mexico to its Idaho mine.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-08-21T12:12:00+00:00",
      "published_display": "21.08 12:12",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "No more doom scrolling or Instagram Stories? A Meta trial loss could end the social media we know",
      "link": "https://www.cnbc.com/2026/08/21/meta-social-media-lawsuit-trial-instagram-facebook.html",
      "description": "\"These trials are often compared to the Big Tobacco lawsuits of the 90s, and the outcome will likely be analogous as well,\" one analyst told CNBC.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T12:11:14+00:00",
      "published_display": "21.08 12:11",
      "sentiment": "neutral",
      "tickers": [
        "META"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Coldcard ships firmware after $114 million bitcoin theft; says AI helped catch more bugs",
      "link": "https://www.coindesk.com/tech/2026/08/21/coldcard-ships-firmware-after-usd114-million-bitcoin-theft-says-ai-helped-catch-more-bugs",
      "description": "Three weeks of review turned up problems unrelated to the flaw that cost users $114 million, but updating still does not make a compromised wallet safe.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/17e2199d1d92db776ca604acd66f78a2a5052896-1754x804.png?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-21T12:10:55+00:00",
      "published_display": "21.08 12:10",
      "sentiment": "negative",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "American consumers are delivering a retail reality check as they laser in on bargains",
      "link": "https://www.marketwatch.com/story/american-consumers-are-delivering-a-retail-reality-check-as-they-laser-in-on-bargains-96816053?mod=mw_rss_topstories",
      "description": "Recent earnings results suggest that the typical shopper is ‘employed, still spending, and increasingly disciplined about it.’",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-90325719",
      "published": "2026-08-21T12:00:00+00:00",
      "published_display": "21.08 12:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Analysts split on whether Bitcoin's surge past key levels signals a new bull run",
      "link": "https://www.coindesk.com/markets/2026/08/21/analysts-split-on-whether-bitcoin-s-surge-past-key-levels-signals-a-new-bull-run",
      "description": "Market watchers say sudden sharp price spikes and forced short liquidations are the classic signs of a bottom, though macro risks still remain.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/b72b4dd95175914ab42f1abbcbe7a1c1085f565e-4000x2250.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-21T11:31:30+00:00",
      "published_display": "21.08 11:31",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why some of America's biggest brands are losing ground in China",
      "link": "https://www.cnbc.com/2026/08/21/us-brands-china-competition.html",
      "description": "Nike, Starbucks and GM have lost ground in China as domestic rivals, geopolitics and changing consumer preferences reshape the market.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T11:30:02+00:00",
      "published_display": "21.08 11:30",
      "sentiment": "negative",
      "tickers": [
        "NKE",
        "SBUX"
      ],
      "sectors": [
        "Consumer Goods"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "The hard truth is that the Clarity Act is an anti-crypto bill",
      "link": "https://www.coindesk.com/opinion/2026/08/21/the-hard-truth-is-that-the-clarity-act-is-an-anti-crypto-bill",
      "description": "After years of stalled bills, misguided enforcement, and catastrophic collapses, almost any comprehensive crypto legislation began to look like progress. But Clarity is turning that hunger for progress into a political trap, argues…",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/66abae4ea7817e1052c710afba1f9fa54651f319-5434x3622.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-21T11:30:00+00:00",
      "published_display": "21.08 11:30",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Bitcoin faces $80,000 test as thinner weekend liquidity looms",
      "link": "https://www.coindesk.com/daybook-us/2026/08/21/bitcoin-faces-usd80-000-test-as-thinner-weekend-liquidity-looms",
      "description": "Your day-ahead look for Aug. 21, 2026",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/d067b6a472aefcd5d9592815bfd5149bbe698626-1920x1080.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-21T11:26:27+00:00",
      "published_display": "21.08 11:26",
      "sentiment": "negative",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hyundai considers Georgia Metaplant expansion to 800,000 units",
      "link": "https://finance.yahoo.com/economy/policy/articles/hyundai-considers-georgia-metaplant-expansion-112106415.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/quartz_855/a8d38bb8c593a6e4824d5f7b76eb6fad.jpg",
      "published": "2026-08-21T11:21:06+00:00",
      "published_display": "21.08 11:21",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Metals Exploration locks in $27M as La India first gold nears",
      "link": "https://www.mining.com/metals-exploration-locks-in-27m-as-la-india-first-gold-nears/",
      "description": "New financing strengthens the junior’s cash position as construction advances despite international shipping delays.",
      "source": "Mining.com",
      "image": "",
      "published": "2026-08-21T11:08:00+00:00",
      "published_display": "21.08 11:08",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nomura-backed Laser Digital wins Japan's first crypto approval in four years",
      "link": "https://www.coindesk.com/policy/2026/08/21/nomura-backed-laser-digital-wins-japan-s-first-crypto-approval-in-four-years",
      "description": "Laser Digital Japan will offer liquidity to domestic crypto providers, with institutional trading services planned to follow as the appetite for crypto in Japan grows.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/0df79e728912cba7bff1db008fd87efc51a77c34-2708x1316.png?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-21T10:38:47+00:00",
      "published_display": "21.08 10:38",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "New York unseats San Francisco as the top market for tech talent, CBRE reports",
      "link": "https://www.cnbc.com/2026/08/21/new-york-san-francisco-tech-talent-cbre.html",
      "description": "AI-related roles now account for nearly one-third of all tech-talent job listings in the U.S., per the new CBRE report.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T10:36:07+00:00",
      "published_display": "21.08 10:36",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Victoria’s Secret reshapes its tech leadership",
      "link": "https://www.retaildive.com/news/victorias-secret-tech-leadership-cto-board-directors/828455/",
      "description": "The retailer tapped former Foot Locker executive Adrian Butler to oversee technology and former Starbucks CTO Gerri Martin-Flickinger to sit on its board.",
      "source": "Retail Dive",
      "image": "https://imgproxy.divecdn.com/QpMkacCdLF1mRmxId7u4C6WqB1qG8NuveNfHkllap1Q/g:nowe:0:114/c:608:344/rs:fill:1600:900:1/Z3M6Ly9kaXZlc2l0ZS1zdG9yYWdlL2RpdmVpbWFnZS9tYWluZV9tYWxsXzIyamFuMjZfLV8xLmpwZWc=.webp",
      "published": "2026-08-21T10:20:00-04:00",
      "published_display": "21.08 10:20",
      "sentiment": "neutral",
      "tickers": [
        "SBUX"
      ],
      "sectors": [
        "Consumer Goods"
      ],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin tops $77,000 as best week since 2023 pulls altcoins along for the ride",
      "link": "https://www.coindesk.com/markets/2026/08/21/bitcoin-tops-usd77-000-as-best-week-since-2023-pulls-altcoins-along-for-the-ride",
      "description": "BTC has gained 24% since Monday and reached the level implied by its inverse head-and-shoulders break, with shorts still taking a contrarian position.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/74e60c18babe89474bec272f69e064623c0b184f-1520x856.png?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-21T10:15:36+00:00",
      "published_display": "21.08 10:15",
      "sentiment": "positive",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "NATO member Romania scrambles F-16 fighter jets to destroy drone near critical European gas project",
      "link": "https://www.cnbc.com/2026/08/21/romania-russia-ukraine-drone-gas-nato.html",
      "description": "It comes weeks after Romania’s Air Force destroyed a Russian drone in its airspace.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-21T10:15:18+00:00",
      "published_display": "21.08 10:15",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Oil Nears $100 as Trump’s ‘Economic D-Day’ Raises the Stakes",
      "link": "https://oilprice.com/Energy/Crude-Oil/Oil-Nears-100-as-Trumps-Economic-D-Day-Raises-the-Stakes.html",
      "description": "Hormuz traffic remains near a standstill as Trump’s ‘Economic D-Day’ campaign pushes Brent closer to $100. Friday, August 21, 2026 Transits through the Strait of Hormuz have been in single digits the entire week, with Trump’s…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-08-21T10:01:15-05:00",
      "published_display": "21.08 10:01",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 65.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Ukrainian Drone Attack Hits Lukoil Refinery Deep in Russia",
      "link": "https://oilprice.com/Latest-Energy-News/World-News/Ukrainian-Drone-Attack-Hits-Lukoil-Refinery-Deep-in-Russia.html",
      "description": "Ukraine overnight hit with drones an oil refinery in the Perm region, deep into Russian territory, as the Ukrainian military has been targeting Russia’s oil processing and exporting facilities on a nearly daily basis in the past few…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-08-21T10:00:00-05:00",
      "published_display": "21.08 10:00",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "India Builds Clean Power Faster Than It Can Use It",
      "link": "https://oilprice.com/Alternative-Energy/Renewable-Energy/India-Builds-Clean-Power-Faster-Than-It-Can-Use-It.html",
      "description": "Numbers Report – August 21, 2026 In the latest edition of the Numbers Report, we will take a look at some of the most interesting figures put out this week in the energy and metals sectors. Each week we’ll dig into some data and provide…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-08-21T09:30:00-05:00",
      "published_display": "21.08 09:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Saudi Oil Exports from Mediterranean Soar with Shuttles North to Avoid Houthis",
      "link": "https://oilprice.com/Latest-Energy-News/World-News/Saudi-Oil-Exports-from-Mediterranean-Soar-with-Shuttles-North-to-Avoid-Houthis.html",
      "description": "Saudi Arabia has boosted its crude oil exports from Egypt’s Mediterranean port of Sidi Kerir by about 33% in the month since the Houthis threatened Saudi oil shipments in the southern Red Sea and the Bab el-Mandeb Strait,…",
      "source": "OilPrice.com",
      "image": "",
      "published": "2026-08-21T09:28:00-05:00",
      "published_display": "21.08 09:28",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    }
  ]
};
