// This file is auto-generated by fetch_news.py — do not edit by hand
const NEWS_DATA = {
  "generated_at": "2026-08-24T13:43:16.718807+00:00",
  "generated_at_display": "24.08.2026 13:43",
  "summary": {
    "total": 80,
    "signal_total": 68,
    "macro_total": 12,
    "positive": 31,
    "negative": 13,
    "neutral": 24,
    "top_tickers": [
      {
        "ticker": "NVDA",
        "count": 7
      },
      {
        "ticker": "SPCX",
        "count": 4
      },
      {
        "ticker": "MSTR",
        "count": 3
      },
      {
        "ticker": "MRVL",
        "count": 3
      },
      {
        "ticker": "COIN",
        "count": 2
      },
      {
        "ticker": "SPY",
        "count": 2
      }
    ],
    "sectors": [
      "AI Infrastructure",
      "Banking & Finance",
      "Big Tech",
      "Cryptocurrencies",
      "ETFs / Indices",
      "Media / Entertainment",
      "Semiconductors",
      "Software / Cloud",
      "Space"
    ],
    "source_counts": {
      "MarketWatch": 6,
      "CNBC": 8,
      "Yahoo Finance": 40,
      "Investing.com": 10,
      "Nasdaq": 13,
      "CoinDesk": 3
    }
  },
  "indices": [
    {
      "name": "S&P 500",
      "symbol": "^GSPC",
      "unit": "index",
      "price": 7646.22,
      "change_abs": -98.84,
      "change_pct": -1.28,
      "spark": [
        7691.54,
        7690.71,
        7681.5498,
        7683.4102,
        7682.6602,
        7682.5298,
        7680.4102,
        7677.0098,
        7674.8999,
        7673.0098,
        7672.25,
        7671.6499,
        7672.2998,
        7680.2598,
        7678.6299,
        7679.2402,
        7683.0898,
        7674.1001,
        7645.9102,
        7646.2202
      ]
    },
    {
      "name": "Dow Jones",
      "symbol": "^DJI",
      "unit": "index",
      "price": 53367.21,
      "change_abs": -92.57,
      "change_pct": -0.17,
      "spark": [
        53229.2305,
        53206.0,
        53154.4883,
        53178.1094,
        53165.9805,
        53189.8086,
        53162.6289,
        53164.8906,
        53188.2812,
        53202.1289,
        53193.6016,
        53239.6914,
        53257.4609,
        53311.4805,
        53322.8984,
        53322.9805,
        53333.4688,
        53279.3281,
        53376.3516,
        53367.2109
      ]
    },
    {
      "name": "Nasdaq Composite",
      "symbol": "^IXIC",
      "unit": "index",
      "price": 25979.22,
      "change_abs": -665.69,
      "change_pct": -2.5,
      "spark": [
        26246.0625,
        26237.1055,
        26199.2773,
        26204.5645,
        26211.3945,
        26208.377,
        26202.4395,
        26192.9434,
        26185.5566,
        26168.9805,
        26161.0762,
        26149.9316,
        26152.9688,
        26186.5957,
        26175.9648,
        26190.2207,
        26206.0703,
        26179.9199,
        25979.5332,
        25979.2188
      ]
    },
    {
      "name": "Russell 2000",
      "symbol": "^RUT",
      "unit": "index",
      "price": 3017.87,
      "change_abs": -39.67,
      "change_pct": -1.3,
      "spark": [
        3007.6638,
        3013.7722,
        3013.2405,
        3013.2056,
        3014.8684,
        3015.1973,
        3014.0205,
        3013.0593,
        3014.2224,
        3014.1624,
        3014.0823,
        3013.5662,
        3015.2297,
        3015.5417,
        3016.8538,
        3018.1243,
        3018.427,
        3017.9939,
        3017.905,
        3017.8708
      ]
    },
    {
      "name": "FTSE 100 (UK)",
      "symbol": "^FTSE",
      "unit": "index",
      "price": 10814.19,
      "change_abs": 93.89,
      "change_pct": 0.88,
      "spark": [
        10831.3096,
        10841.75,
        10829.7998,
        10829.3496,
        10832.9199,
        10836.3896,
        10838.8604,
        10844.0703,
        10834.7598,
        10829.9297,
        10836.1699,
        10829.2305,
        10820.6396,
        10819.9297,
        10819.1504,
        10813.7998,
        10809.0596,
        10800.3604,
        10814.8398,
        10814.1904
      ]
    },
    {
      "name": "DAX (Germany)",
      "symbol": "^GDAXI",
      "unit": "index",
      "price": 26095.8,
      "change_abs": -242.81,
      "change_pct": -0.92,
      "spark": [
        26126.8301,
        26154.2207,
        26125.5,
        26134.8008,
        26149.2793,
        26147.4902,
        26153.2402,
        26139.3398,
        26134.9004,
        26117.4609,
        26120.0293,
        26147.2793,
        26135.4805,
        26126.2402,
        26132.1602,
        26110.7402,
        26112.3203,
        26080.2598,
        26093.6406,
        26095.8008
      ]
    },
    {
      "name": "Euro Stoxx 50",
      "symbol": "^STOXX50E",
      "unit": "index",
      "price": 6449.89,
      "change_abs": -18.28,
      "change_pct": -0.28,
      "spark": [
        6458.0498,
        6463.8999,
        6456.4199,
        6456.77,
        6460.1099,
        6458.9502,
        6461.3501,
        6460.0498,
        6458.98,
        6455.2402,
        6457.7598,
        6462.3701,
        6457.1201,
        6454.5498,
        6455.7998,
        6451.3999,
        6449.6401,
        6442.9199,
        6450.5898,
        6449.8901
      ]
    },
    {
      "name": "Nikkei 225 (Japan)",
      "symbol": "^N225",
      "unit": "index",
      "price": 65528.09,
      "change_abs": -1932.64,
      "change_pct": -2.86,
      "spark": [
        66089.2734,
        66068.3672,
        66032.6016,
        65775.0234,
        65971.3281,
        65972.7188,
        65968.7109,
        65649.5078,
        65592.7734,
        65771.3672,
        65673.5469,
        65673.8906,
        65637.9922,
        65782.4688,
        65711.3984,
        65579.2891,
        65566.4297,
        65530.7695,
        65537.3281,
        65528.0898
      ]
    },
    {
      "name": "Hang Seng (Hong Kong)",
      "symbol": "^HSI",
      "unit": "index",
      "price": 25517.33,
      "change_abs": 64.1,
      "change_pct": 0.25,
      "spark": [
        25511.3906,
        25492.3203,
        25455.3809,
        25458.6699,
        25456.5391,
        25465.7207,
        25465.2305,
        25498.2598,
        25498.5996,
        25481.6699,
        25472.7891,
        25503.1504,
        25503.9004,
        25535.6309,
        25544.1699,
        25531.1309,
        25503.9805,
        25498.0391,
        25485.2598,
        25517.3301
      ]
    },
    {
      "name": "Gold (futures)",
      "symbol": "GC=F",
      "unit": "index",
      "price": 4728.2,
      "change_abs": 238.8,
      "change_pct": 5.32,
      "spark": [
        4697.2998,
        4691.3999,
        4695.2998,
        4702.3999,
        4704.8999,
        4700.7002,
        4701.2998,
        4700.2998,
        4699.2002,
        4704.0,
        4716.7002,
        4715.0,
        4715.5,
        4719.3999,
        4715.0,
        4720.7002,
        4735.0,
        4730.1001,
        4732.7998,
        4728.2002
      ]
    },
    {
      "name": "WTI Crude Oil (futures)",
      "symbol": "CL=F",
      "unit": "index",
      "price": 85.97,
      "change_abs": 0.14,
      "change_pct": 0.16,
      "spark": [
        85.06,
        85.39,
        85.32,
        85.15,
        85.08,
        84.99,
        85.2,
        85.39,
        85.22,
        85.49,
        85.15,
        85.38,
        85.52,
        85.46,
        85.62,
        85.54,
        85.51,
        85.91,
        85.85,
        85.97
      ]
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC-USD",
      "unit": "index",
      "price": 78249.64,
      "change_abs": 5216.88,
      "change_pct": 7.14,
      "spark": [
        77271.3672,
        77417.5391,
        77457.2266,
        77540.8828,
        77831.3594,
        77843.9219,
        77713.3203,
        77608.8594,
        77815.7891,
        77829.8672,
        78559.0391,
        78431.3672,
        78125.8984,
        78430.4766,
        78719.1406,
        79136.3672,
        79191.0469,
        78996.9531,
        78231.2266,
        78249.6406
      ]
    },
    {
      "name": "10-Year US Treasury Yield",
      "symbol": "^TNX",
      "unit": "yield_pct",
      "price": 0.47,
      "change_abs": 0.0,
      "change_pct": 0.17,
      "spark": [
        0.473,
        0.4734,
        0.4738,
        0.4734,
        0.4732,
        0.4734,
        0.4734,
        0.4736,
        0.4742,
        0.474,
        0.474,
        0.4738,
        0.4738,
        0.4738,
        0.4708,
        0.4712,
        0.4714,
        0.4716,
        0.4714,
        0.4714
      ]
    },
    {
      "name": "VIX (Fear Index)",
      "symbol": "^VIX",
      "unit": "index",
      "price": 15.85,
      "change_abs": 0.01,
      "change_pct": 0.06,
      "spark": [
        15.88,
        15.87,
        15.92,
        15.89,
        15.89,
        15.91,
        15.93,
        15.94,
        15.95,
        16.0,
        16.04,
        15.89,
        15.9,
        15.92,
        15.87,
        15.93,
        15.89,
        15.85,
        15.85,
        15.85
      ]
    }
  ],
  "items": [
    {
      "title": "This has been one of the most affordable U.S. cities to buy a home for more than 134 years",
      "link": "https://www.marketwatch.com/story/this-has-been-one-of-the-most-affordable-u-s-cities-to-buy-a-home-for-the-past-134-years-0c52895a?mod=mw_rss_topstories",
      "description": "Home prices in America have changed dramatically over the last century — but the Midwest has remained a bastion of affordability through it all.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-04079702",
      "published": "2026-08-24T13:39:00+00:00",
      "published_display": "24.08 13:39",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "California AG Rob Bonta cancels Paramount settlement meeting, citing 'lack of good faith'",
      "link": "https://www.cnbc.com/2026/08/24/california-ag-bonta-paramount-settlement-meeting.html",
      "description": "California AG Rob Bonta was scheduled to meet with Paramount representatives on Monday, he said, but canceled the meeting.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T13:33:29+00:00",
      "published_display": "24.08 13:33",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Coinbase Has Been Choppy All Year: One Analyst Expects Nearly 80% Gains Ahead Anyway",
      "link": "https://finance.yahoo.com/markets/crypto/articles/coinbase-choppy-one-analyst-expects-133117184.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/f9684edead350e56a2aabfad96bd04d8.jpg",
      "published": "2026-08-24T13:31:17+00:00",
      "published_display": "24.08 13:31",
      "sentiment": "positive",
      "tickers": [
        "COIN"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Here are two trades to make ahead of a critical week for markets as Nvidia results and Jackson Hole loom",
      "link": "https://www.marketwatch.com/story/here-are-two-trades-to-make-ahead-of-a-critical-week-for-markets-as-nvidia-results-and-jackson-hole-loom-8ac3653c?mod=mw_rss_topstories",
      "description": "There’s a way to play more interest rate angst or an Nvidia inspired tech bounce says Evercore ISI",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-04491989",
      "published": "2026-08-24T13:31:00+00:00",
      "published_display": "24.08 13:31",
      "sentiment": "neutral",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "The AI Opportunity Qualcomm Investors May Be Underestimating",
      "link": "https://finance.yahoo.com/markets/stocks/articles/ai-opportunity-qualcomm-investors-may-133001759.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/2e5d77f28e5f231c92e932db466a63d6.jpg",
      "published": "2026-08-24T13:30:01+00:00",
      "published_display": "24.08 13:30",
      "sentiment": "positive",
      "tickers": [
        "QCOM"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Strategy earmarks $1.6 billion cash pool for treasury operations, buybacks",
      "link": "https://finance.yahoo.com/markets/crypto/articles/strategy-earmarks-1-6-billion-132902331.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/reuters-finance.com/ffd4ed054bd02ec4d38887a0c71c73f0.jpg",
      "published": "2026-08-24T13:29:02+00:00",
      "published_display": "24.08 13:29",
      "sentiment": "neutral",
      "tickers": [
        "MSTR"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Yes, yields are important, but don't forget about Nvidia",
      "link": "https://www.cnbc.com/2026/08/24/yes-yields-are-important-but-dont-forget-about-nvidia.html",
      "description": "Lately, Wall Street's eyes have been fixed on the bond market, and rightfully so. But there's another major catalyst that could sway the market this week.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T13:26:09+00:00",
      "published_display": "24.08 13:26",
      "sentiment": "neutral",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Oil falls ahead of US announcement of new sanctions on Iran",
      "link": "https://finance.yahoo.com/news/oil-falls-1-ahead-us-231835385.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/reuters.com/a3b73541371e3888d82fb38762954110.jpg",
      "published": "2026-08-24T13:25:59+00:00",
      "published_display": "24.08 13:25",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cantor Fitzgerald Just Named This Chip Giant Its Top Semiconductor Pick",
      "link": "https://www.investing.com/news/stock-market-news/cantor-fitzgerald-just-named-this-chip-giant-its-top-semiconductor-pick-93CH-4873653",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEL3F0GL_L.jpg",
      "published": "2026-08-24T13:25:06",
      "published_display": "24.08 13:25",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "U.S. Trade Rep Greer blames Canada for failed tariff talks: 'They wanted more'",
      "link": "https://www.cnbc.com/2026/08/24/trump-canada-trade-tariffs-greer.html",
      "description": "Canadian negotiators left Washington Friday without a deal to prevent President Donald Trump from enacting new 50% tariffs on about $20 billion worth of goods.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T13:24:51+00:00",
      "published_display": "24.08 13:24",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Xpeng forecast disappoints as China EV competition heats up",
      "link": "https://www.investing.com/news/stock-market-news/xpeng-forecast-disappoints-as-china-ev-competition-heats-up-4873652",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM7N0Y8_L.jpg",
      "published": "2026-08-24T13:24:51",
      "published_display": "24.08 13:24",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "SpaceX Falls 3% Despite Trump’s 1,000-Launch Order, AST SpaceMobile Drops 3%, Rocket Lab Slips",
      "link": "https://finance.yahoo.com/markets/stocks/articles/spacex-falls-3-despite-trump-132448656.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/f2814d8df914ea78b03c53eadc49471e.png",
      "published": "2026-08-24T13:24:48+00:00",
      "published_display": "24.08 13:24",
      "sentiment": "negative",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "US FTC to file order resolving litigation against Zillow, Redfin",
      "link": "https://www.investing.com/news/stock-market-news/us-ftc-to-file-order-resolving-litigation-against-zillow-redfin-4873634",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM7N0XY_L.jpg",
      "published": "2026-08-24T13:24:32",
      "published_display": "24.08 13:24",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "AB InBev invests in New York Cutwater production",
      "link": "https://finance.yahoo.com/markets/stocks/articles/ab-inbev-invests-york-cutwater-132429706.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/just_drinks_442/5eff49db5ae0482daf8713532be228a0.jpg",
      "published": "2026-08-24T13:24:29+00:00",
      "published_display": "24.08 13:24",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "KLA (KLAC) Gains From Advanced Nodes, HBM and Packaging",
      "link": "https://finance.yahoo.com/markets/stocks/articles/kla-klac-gains-advanced-nodes-132424736.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/117415b1841a6c1ecf8d94495ff3999f.jpg",
      "published": "2026-08-24T13:24:24+00:00",
      "published_display": "24.08 13:24",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stocks Settle Higher as Crude Oil Prices Stabilize",
      "link": "https://www.nasdaq.com/articles/stocks-settle-higher-crude-oil-prices-stabilize",
      "description": "The S&P 500 Index ($SPX ) (SPY ) closed up by +0.43% on Friday, the Dow Jones Industrial Average ($DOWI ) (DIA ) closed up by +0.98%, and the Nasdaq 100 Index ($IUXX ) (QQQ ) closed up by +0.33%. E-mini S&P futures (ESU26 ) rose +0.37%,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T13:24:13+00:00",
      "published_display": "24.08 13:24",
      "sentiment": "positive",
      "tickers": [
        "SPY",
        "QQQ",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "“You Ought to Be Ashamed of Yourself, Lady”: Dave Ramsey to Mom Pressuring Son to Cosign an $800,000 Mortgage",
      "link": "https://finance.yahoo.com/small-business/articles/ought-ashamed-yourself-lady-dave-132317673.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/c59da5182db856366f71e8b48a5d79ae.jpg",
      "published": "2026-08-24T13:23:17+00:00",
      "published_display": "24.08 13:23",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Anthropic Wants Investors to Buy Into a $2 Trillion Dream—But a Wall Street Veteran Says SpaceX’s IPO Offers a Warning for AI Investors (UPDATED)",
      "link": "https://finance.yahoo.com/technology/ai/articles/exclusive-anthropics-2-trillion-valuation-130029619.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/benzinga_private_markets_129/b4608e5acc4618e10fa1a9d085d3ab1b.jpg",
      "published": "2026-08-24T13:23:14+00:00",
      "published_display": "24.08 13:23",
      "sentiment": "neutral",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Applied Optoelectronics Sinks 12% on $600M Equity Offering, Lumentum and Coherent Drop 5%",
      "link": "https://finance.yahoo.com/markets/stocks/articles/applied-optoelectronics-sinks-12-600m-132235988.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/83c597fdd93a0ae3e24978750aa03289.jpg",
      "published": "2026-08-24T13:22:35+00:00",
      "published_display": "24.08 13:22",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Lam Research (LRCX) Sees Strong Growth Extend Into 2027 as AI Spending Accelerates",
      "link": "https://finance.yahoo.com/technology/ai/articles/lam-research-lrcx-sees-strong-132142425.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/64c7f38b69bd626677038cbbc1da5e08.jpg",
      "published": "2026-08-24T13:21:42+00:00",
      "published_display": "24.08 13:21",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bessent Quietly Built a $950 Billion War Chest Sitting In An Account At The Fed. Now We Know What It’s For",
      "link": "https://finance.yahoo.com/economy/policy/articles/bessent-quietly-built-950-billion-132130268.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/f81a4a5311572077bb4c087759e37b85",
      "published": "2026-08-24T13:21:30+00:00",
      "published_display": "24.08 13:21",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Mondelez CEO Dirk Van De Put Sells 134,000 Shares for $8.5 Million",
      "link": "https://finance.yahoo.com/markets/stocks/articles/mondelez-ceo-dirk-van-put-132001850.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/6df4b60a8ec56b07e8006b55fcfdc96a.png",
      "published": "2026-08-24T13:20:01+00:00",
      "published_display": "24.08 13:20",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Chewy Is Down 80% From Its All-Time High. Is This a No-Brainer Buy for Growth Stock Investors?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/chewy-down-80-time-high-132000486.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/c721cc2d5a81c98f719b150f888c2f8e.jpg",
      "published": "2026-08-24T13:20:00+00:00",
      "published_display": "24.08 13:20",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Intuit earnings preview: Can FQ4 results unlock more upside after recent rally?",
      "link": "https://www.investing.com/news/stock-market-news/intuit-earnings-preview-can-fq4-results-unlock-more-upside-after-recent-rally-93CH-4873635",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEL7K0WS_L.jpg",
      "published": "2026-08-24T13:19:09",
      "published_display": "24.08 13:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Wheat Fades Lower into the Weekend",
      "link": "https://www.nasdaq.com/articles/wheat-fades-lower-weekend",
      "description": "The wheat complex is in the red across the three exchanges on Friday. Chicago SRW contracts were fractionally to 1 ¼ cents lower on Friday, with September up 6 ¾ cents on the week. KC HRW futures posted losses of 1 ¾ to 6 cents on the…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T13:18:45+00:00",
      "published_display": "24.08 13:18",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Wheat Facing Friday Pressure",
      "link": "https://www.nasdaq.com/articles/wheat-facing-friday-pressure",
      "description": "The wheat complex is in the red across the three exchanges on Friday. Chicago SRW contracts are 4 to 6 cents lower so far on Friday. KC HRW futures are trading with contracts 7 to 9 cents in the red. MPLS spring wheat is down 5 to 7…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T13:18:45+00:00",
      "published_display": "24.08 13:18",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Corn Pushing Higher into the Weekend",
      "link": "https://www.nasdaq.com/articles/corn-pushing-higher-weekend",
      "description": "Corn futures are holding onto 1 to 2 cent gains across most contracts on Friday. The CmdtyView national average Cash Corn price is up 1 ½ cents at $4.52 ½. USDA reported 205,000 MT of corn sold during the reporting period to unknown…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T13:18:45+00:00",
      "published_display": "24.08 13:18",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump administration moves to impose more than $100,000 fee for H-1B worker visas",
      "link": "https://www.investing.com/news/stock-market-news/trump-administration-moves-to-impose-more-than-100000-fee-for-h1b-worker-visas-4873633",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM7N0Y0_L.jpg",
      "published": "2026-08-24T13:18:34",
      "published_display": "24.08 13:18",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Bessent could tap near $1 trillion Treasury General Account to fund bond buybacks, sources said",
      "link": "https://www.cnbc.com/2026/08/24/bessent-1-trillion-treasury-general-account-bond-buybacks.html",
      "description": "Using the TGA would provide the Treasury with considerable firepower to influence long-term bond yields.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T13:17:35+00:00",
      "published_display": "24.08 13:17",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Nvidia raising AI server prices more than 15% amid memory costs",
      "link": "https://finance.yahoo.com/technology/ai/articles/nvidia-raising-ai-server-prices-131547349.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/quartz_855/fa7df46af0489eb1b0c7f806f0bdff5b.jpg",
      "published": "2026-08-24T13:15:47+00:00",
      "published_display": "24.08 13:15",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Micron’s CEO Says Memory Is No Longer a Commodity, and He Is Betting $10 Billion On It",
      "link": "https://finance.yahoo.com/technology/ai/articles/micron-ceo-says-memory-no-131547668.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/ae88f18cbf21b60bbd49faa0cb43272d",
      "published": "2026-08-24T13:15:47+00:00",
      "published_display": "24.08 13:15",
      "sentiment": "positive",
      "tickers": [
        "MU"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 55.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Navios Maritime (NMM) Q2 2026 Earnings Call Transcript",
      "link": "https://finance.yahoo.com/markets/stocks/articles/navios-maritime-nmm-q2-2026-131440181.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/a726d4819c9ce56f8dbd126ba4eb20c8.png",
      "published": "2026-08-24T13:14:40+00:00",
      "published_display": "24.08 13:14",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Alibaba Stock Falls As AI Push Drives $10 Billion Share Sale",
      "link": "https://www.investors.com/news/technology/alibaba-stock-falls-as-ai-push-drives-10-billion-share-sale/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/904c745ab98019e8c704bb0851217506.jpg",
      "published": "2026-08-24T13:13:52+00:00",
      "published_display": "24.08 13:13",
      "sentiment": "negative",
      "tickers": [
        "BABA"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 60.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Can AMD (AMD) Win From the Shift Toward More CPU-Heavy AI Data Centers?",
      "link": "https://finance.yahoo.com/technology/articles/amd-amd-win-shift-toward-131307134.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/5d959ba60ef2acc25a19e5cd0a23aafc.jpg",
      "published": "2026-08-24T13:13:07+00:00",
      "published_display": "24.08 13:13",
      "sentiment": "neutral",
      "tickers": [
        "AMD"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "American Resources' ReElement adds seven executives",
      "link": "https://finance.yahoo.com/technology/articles/american-resources-reelement-adds-seven-131200258.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/proactive_us_504/0bd273074b09474966d14ff6db89368a.jpg",
      "published": "2026-08-24T13:12:00+00:00",
      "published_display": "24.08 13:12",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The Hidden Reason SPHY and SPYD Diverged So Sharply in 2026",
      "link": "https://finance.yahoo.com/markets/stocks/articles/hidden-reason-sphy-spyd-diverged-131049817.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/54ff122342d8c95a7e3040b0163a7b5a.jpg",
      "published": "2026-08-24T13:10:49+00:00",
      "published_display": "24.08 13:10",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "First Majestic Silver vs. MP Materials: Which Metals Stock Is a Better Buy in 2026?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/first-majestic-silver-vs-mp-130957285.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/bb9fb85ff96c96d3b730b6ff74e8b6fa.png",
      "published": "2026-08-24T13:09:57+00:00",
      "published_display": "24.08 13:09",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "U.S. Steel Stocks Nucor, Steel Dynamics Rally As Canada Trade Talks Collapse",
      "link": "https://www.investors.com/news/u-s-steel-stocks-nucor-steel-dynamics-canada-trade-talks-collapse/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/35ba871737dc4a4f11b561424d5268e6.jpg",
      "published": "2026-08-24T13:09:39+00:00",
      "published_display": "24.08 13:09",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 70.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Marvell Could Give Investors A Reason To Celebrate On August 27th",
      "link": "https://finance.yahoo.com/markets/stocks/articles/marvell-could-investors-reason-celebrate-130556202.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/7317409b54b4e09ed1d3d866c2cdd588.jpg",
      "published": "2026-08-24T13:05:56+00:00",
      "published_display": "24.08 13:05",
      "sentiment": "positive",
      "tickers": [
        "MRVL"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin and ethereum prices today, Monday, August 24, 2026: Prices rising, as investors look for more Fed clues this week",
      "link": "https://finance.yahoo.com/personal-finance/investing/article/bitcoin-and-ethereum-prices-today-monday-august-24-2026-prices-rising-as-investors-look-for-more-fed-clues-this-week-130538704.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/8IgKHs0.oTwPcn40eBVnmg--~B/aD00MDg7dz02MTI7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/bitcoin_1_3688.jpg",
      "published": "2026-08-24T13:05:38+00:00",
      "published_display": "24.08 13:05",
      "sentiment": "positive",
      "tickers": [
        "BTC",
        "ETH"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The Big Difference Between Broadcom and Marvell Technology",
      "link": "https://finance.yahoo.com/markets/stocks/articles/big-difference-between-broadcom-marvell-130518896.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/115c82074b909c1335df4e84ce78a241.jpg",
      "published": "2026-08-24T13:05:18+00:00",
      "published_display": "24.08 13:05",
      "sentiment": "neutral",
      "tickers": [
        "AVGO",
        "MRVL"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Samsung Electronics stock drops after shareholder return plan disappoints",
      "link": "https://finance.yahoo.com/markets/stocks/articles/samsung-electronics-stock-drops-shareholder-130506722.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/quartz_855/e736934fd1c60191aa5389b940caab03.jpg",
      "published": "2026-08-24T13:05:06+00:00",
      "published_display": "24.08 13:05",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Strategy Leaves Bitcoin Holdings Unchanged As Price Rises",
      "link": "https://finance.yahoo.com/markets/crypto/articles/strategy-leaves-bitcoin-holdings-unchanged-130500704.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/cryptoprowl_304/63237ad213bf73d32f7c0e168ce84051.jpg",
      "published": "2026-08-24T13:05:00+00:00",
      "published_display": "24.08 13:05",
      "sentiment": "neutral",
      "tickers": [
        "BTC",
        "MSTR"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "This Fund Exits Intuit (INTU) Amid Concerns of AI Disruption to TurboTax’s Moat",
      "link": "https://finance.yahoo.com/markets/stocks/articles/fund-exits-intuit-intu-amid-130402105.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/014908c92699c75defe19d3897fbc058.jpg",
      "published": "2026-08-24T13:04:02+00:00",
      "published_display": "24.08 13:04",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Yields are the highest they’ve been in years — but are bonds cheap enough to buy? Two strategists disagree.",
      "link": "https://www.marketwatch.com/story/theyre-the-highest-theyve-been-in-years-but-are-bonds-cheap-enough-to-buy-here-two-strategists-disagree-348fe330?mod=mw_rss_topstories",
      "description": "Bond yields are driven by the market’s estimate of the average federal funds rate over the next 10 years, plus some compensation for the risks associated with predicting that. Barclays finds bonds at fair value but not cheap yet.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-14849691",
      "published": "2026-08-24T13:04:00+00:00",
      "published_display": "24.08 13:04",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Morgan Stanley Flags Five European Software Stocks to Buy in Second-Half Outlook",
      "link": "https://www.investing.com/news/stock-market-news/morgan-stanley-flags-five-european-software-stocks-to-buy-in-secondhalf-outlook-93CH-4873571",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPED6J1UU_M.jpg",
      "published": "2026-08-24T13:03:40",
      "published_display": "24.08 13:03",
      "sentiment": "positive",
      "tickers": [
        "MS"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cathie Wood's ARK Goes On $27 Million SpaceX Shopping Spree",
      "link": "https://www.investors.com/news/cathie-wood-spacex-tesla-ark-invest-etf/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/325a8766791a258753f13bf38157201f.jpg",
      "published": "2026-08-24T13:03:10+00:00",
      "published_display": "24.08 13:03",
      "sentiment": "positive",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The Treasury’s bond-market intervention isn’t working. So what comes next?",
      "link": "https://www.marketwatch.com/story/the-treasurys-bond-market-intervention-isnt-working-so-what-comes-next-ba5e132a?mod=mw_rss_topstories",
      "description": "You can’t just sweep $40 trillion in U.S. national debt under a rug and forget about it — or so the bond market appears to be telling Treasury Secretary Scott Bessent.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-97802719",
      "published": "2026-08-24T13:02:00+00:00",
      "published_display": "24.08 13:02",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 70.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Top insider buys and sells disclosed on Friday",
      "link": "https://www.investing.com/news/stock-market-news/top-insider-buys-and-sells-disclosed-on-friday-93CH-4873558",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LisaSupresidentandCEOofAMD_800x533_L_1644852645.jpg",
      "published": "2026-08-24T13:01:33",
      "published_display": "24.08 13:01",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Coinbase-backed crypto advocacy group endorses 32 US midterm candidates",
      "link": "https://www.investing.com/news/stock-market-news/coinbasebacked-crypto-advocacy-group-endorses-32-us-midterm-candidates-4873491",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/trkd-images/LYNXMPEM7N0W8_L.jpg",
      "published": "2026-08-24T13:00:50",
      "published_display": "24.08 13:00",
      "sentiment": "neutral",
      "tickers": [
        "COIN"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Gemini crypto exchange review 2026: Bank-grade security comes at a price",
      "link": "https://finance.yahoo.com/personal-finance/investing/review/gemini-crypto-review-130000290.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/B.bk3Tob3vTbJeDju0MuOA--~B/aD00MTYwO3c9NjI0MDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-08/8340715d-431f-4cd3-b2d6-fd4d0805ba27",
      "published": "2026-08-24T13:00:00+00:00",
      "published_display": "24.08 13:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Tom Lee's Bitmine buys $81 million of ETH in largest weekly haul since early July",
      "link": "https://www.coindesk.com/business/2026/08/24/tom-lee-s-bitmine-buys-usd81-million-of-eth-in-largest-weekly-haul-since-early-july",
      "description": "The treasury firm stepped up its ETH buying as Tom Lee said the crypto’s 30% weekly rally could signal a larger move ahead.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/9d7bd39b2982649e7e43cc0537c507eb62abc21c-2048x1152.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-24T12:59:55+00:00",
      "published_display": "24.08 12:59",
      "sentiment": "positive",
      "tickers": [
        "ETH"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cotton Closes Steady on Friday",
      "link": "https://www.nasdaq.com/articles/cotton-closes-steady-friday",
      "description": "Cotton futures were up 1 to 7 points in the front months on Friday, with contracts down 8 points to 20 points higher. December was up 355 points on the week. Crude oil was down 19 cents with the US dollar index $0.063 lower. Commitment…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:12+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hogs Push Higher into the Weekend",
      "link": "https://www.nasdaq.com/articles/hogs-push-higher-weekend",
      "description": "Lean hog futures posted gains of 50 to 77 cents across most contracts on Friday, with October slipping 87 cents on the week. USDA’s national base hog price was reported at $94.27 in the Friday PM report, up $1.93 from the day prior. The…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:12+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cattle Pull off Early Friday Lows, as Cattle on Feed Shows Fewer Placements",
      "link": "https://www.nasdaq.com/articles/cattle-pull-early-friday-lows-cattle-feed-shows-fewer-placements",
      "description": "Live cattle futures pull off early losses on Friday, with contracts closing down 30 cents to $1.15 higher. October was up 95 cents on the week. Cash trade has picked up a few at $355-360 dressed and $223-227. Feeder cattle futures were…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:12+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Soybeans Firm Higher Late on Friday",
      "link": "https://www.nasdaq.com/articles/soybeans-firm-higher-late-friday",
      "description": "Soybeans pushed higher late on Friday, with contracts up 1 to 4 ¼ cents at the close. September was up 47 ¼ cents on the week, with November 47 cents higher. September options expired today. The cmdtyView national average Cash Bean…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:12+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Corn Rallies into Friday’s Close Following Week of Weaker Tour Yields",
      "link": "https://www.nasdaq.com/articles/corn-rallies-fridays-close-following-week-weaker-tour-yields",
      "description": "Corn futures found late strength on Friday with contracts 2 ¾ to 6 ½ cents higher across the board. September was 24 ¾ cents higher on the week, with December rallying 25 ¼ cents. September options expired today. The CmdtyView national…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:11+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cotton Trading Steady on Friday",
      "link": "https://www.nasdaq.com/articles/cotton-trading-steady-friday",
      "description": "Cotton futures are holding mostly steady on Friday after early gains, with contracts down 7 points to 10 points higher, and October up 56 points. Crude oil is down 5 cents with the US dollar index $0.073 higher. Export Sales data from…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:11+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hogs Firming into the Weekend",
      "link": "https://www.nasdaq.com/articles/hogs-firming-weekend",
      "description": "Lean hog futures are showing 70 to 90 cent gains in most front months on Friday. USDA’s national base hog price was reported at $94.58 in the Friday AM report, up $1.83 from the day prior. The CME Lean Hog Index was down another 24…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:11+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Soybeans Slipping on Friday, Ignoring Large Export Sale Announcements",
      "link": "https://www.nasdaq.com/articles/soybeans-slipping-friday-ignoring-large-export-sale-announcements",
      "description": "Soybeans are trading with midday losses of 1 to 3 cents at Friday’s midday. September options expire today. The cmdtyView national average Cash Bean price is down 3/4 cent at $11.98 3/4. Soymeal futures are back up $1 to $1.20, as Soy…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:57:10+00:00",
      "published_display": "24.08 12:57",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Tech stocks today: All eyes on Nvidia as Meta trial resumes",
      "link": "https://finance.yahoo.com/technology/live/tech-stocks-today-all-eyes-on-nvidia-as-meta-trial-resumes-125406169.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/ki.mEL68Jn4oa3TnI5Z4Sg--~B/aD0zMzkxO3c9NTAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-08/b5a96516-7876-4c93-8b8e-5e1b83cccd16",
      "published": "2026-08-24T12:54:06+00:00",
      "published_display": "24.08 12:54",
      "sentiment": "neutral",
      "tickers": [
        "NVDA",
        "META"
      ],
      "sectors": [
        "Big Tech",
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stock Market Today: Dow Falls Ahead of 'Economic D-Day'; Alibaba Slides On Offering (Live Coverage)",
      "link": "https://www.investors.com/market-trend/stock-market-today/dow-jones-sp500-nasdaq-economic-d-day-alibaba-stock-baba/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/4f1fa106a49c603c17f0aadb20cc8971.jpg",
      "published": "2026-08-24T12:53:27+00:00",
      "published_display": "24.08 12:53",
      "sentiment": "negative",
      "tickers": [
        "BABA"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Applied Materials (AMAT) Is Positioned to Capture More of the AI Chip Manufacturing Boom",
      "link": "https://finance.yahoo.com/technology/ai/articles/applied-materials-amat-positioned-capture-125326878.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/baace31f0e29cc385fd4eec1d0fcbd68.jpg",
      "published": "2026-08-24T12:53:26+00:00",
      "published_display": "24.08 12:53",
      "sentiment": "positive",
      "tickers": [
        "AMAT"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "New Solana vote could ramp daily SOL burns to $800,000 and slow new token creation",
      "link": "https://www.coindesk.com/tech/2026/08/24/new-solana-vote-could-ramp-daily-sol-burns-to-usd800-000-and-slow-new-token-creation",
      "description": "Two of the three proposals would reduce SOL supply growth by speeding up Solana’s inflation decline and raising daily fee burns from about 650 SOL to as much as 9,000 SOL.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/9a77266875bd5ba03807c057c4d6412491668d63-3622x2717.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-24T12:52:30+00:00",
      "published_display": "24.08 12:52",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Silver prices today, Monday, August 24, 2026: Why silver remains on a roll, up over 18% month-over-month",
      "link": "https://finance.yahoo.com/personal-finance/investing/article/silver-prices-today-monday-august-24-2026-why-silver-remains-on-a-roll-up-over-18-month-over-month-124600654.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/os/creatr-uploaded-images/2024-04/21b3a190-027e-11ef-bbb5-a0f6297c401d",
      "published": "2026-08-24T12:46:00+00:00",
      "published_display": "24.08 12:46",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dow Jones, Nasdaq, S&P 500 preview: Nvidia results, Jackson Hole take center stage",
      "link": "https://www.investing.com/news/stock-market-news/dow-jones-nasdaq-sp-500-preview-nvidia-results-jackson-hole-take-center-stage-4873523",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEM4Q092_L.jpg",
      "published": "2026-08-24T12:45:54",
      "published_display": "24.08 12:45",
      "sentiment": "neutral",
      "tickers": [
        "NVDA",
        "SPY",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices",
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Saudi Arabia stocks higher at close of trade; Tadawul All Share up 0.86%",
      "link": "https://www.investing.com/news/stock-market-news/saudi-arabia-stocks-higher-at-close-of-trade-tadawul-all-share-up-086-4873520",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC4208E_M.jpg",
      "published": "2026-08-24T12:45:03",
      "published_display": "24.08 12:45",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Here are Monday's biggest analyst calls: Nvidia, Jersey Mike's, Dell, Chipotle, Marvell, CoreWeave & more",
      "link": "https://www.cnbc.com/2026/08/24/mondays-top-analyst-calls-on-wall-street-include-nvidia.html",
      "description": "Here are the biggest analyst calls on Wall Street on Monday.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T12:40:11+00:00",
      "published_display": "24.08 12:40",
      "sentiment": "neutral",
      "tickers": [
        "NVDA",
        "MRVL",
        "CRWV",
        "DELL"
      ],
      "sectors": [
        "AI Infrastructure",
        "Semiconductors"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Gold prices today, Monday, August 24, 2026: 'Gold to stay hot through the end of the month'",
      "link": "https://finance.yahoo.com/personal-finance/investing/article/gold-prices-today-monday-august-24-2026-gold-to-stay-hot-through-the-end-of-the-month-123911561.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/zXVwgsaFyGNgvrXU6TElCg--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/monday.png",
      "published": "2026-08-24T12:39:11+00:00",
      "published_display": "24.08 12:39",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Jim Cramer's top 10 things to watch in the stock market Monday",
      "link": "https://www.cnbc.com/2026/08/24/jim-cramers-top-10-things-to-watch-in-the-stock-market-monday.html",
      "description": "Nvidia reports earnings this week, but it's not the only thing that matters to the AI trade.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T12:39:03+00:00",
      "published_display": "24.08 12:39",
      "sentiment": "neutral",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "There are six stocks that hedge funds and mutual funds are both overweight — and SpaceX is one",
      "link": "https://www.marketwatch.com/story/there-are-six-stocks-that-hedge-funds-and-mutual-funds-are-both-overweight-and-spacex-is-one-2a17ffb1?mod=mw_rss_topstories",
      "description": "SpaceX, trading at 93 times next year’s estimated earnings, seems hardly the stock to unite both short-term-focused hedge-fund managers and more long-term-oriented mutual-fund managers.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-52803374",
      "published": "2026-08-24T12:37:00+00:00",
      "published_display": "24.08 12:37",
      "sentiment": "neutral",
      "tickers": [
        "SPCX"
      ],
      "sectors": [
        "Space"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Trump Media CEO defends selling faster access to president's Truth Social posts, says more have signed up",
      "link": "https://www.cnbc.com/2026/08/24/trump-media-ceo-truth-api.html",
      "description": "Trump Media interim CEO Kevin McGurn defended his company offering faster access to President Donald Trump's Truth Social posts.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T12:35:50+00:00",
      "published_display": "24.08 12:35",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Nasdaq (NDAQ) Has Quietly Built a More Durable Business Beyond Trading",
      "link": "https://finance.yahoo.com/markets/stocks/articles/nasdaq-ndaq-quietly-built-more-123537840.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/91955f44d75d88f33e1647c18b0fe457.jpg",
      "published": "2026-08-24T12:35:37+00:00",
      "published_display": "24.08 12:35",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Is Adobe (ADBE) Losing Its Edge Despite Strong AI Adoption?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/adobe-adbe-losing-edge-despite-123249439.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/2b5b7ecf073968982fd33d6ff1961546.jpg",
      "published": "2026-08-24T12:32:49+00:00",
      "published_display": "24.08 12:32",
      "sentiment": "neutral",
      "tickers": [
        "ADBE"
      ],
      "sectors": [
        "Software / Cloud"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Santoli: Why all the fuss about bond yields is happening now",
      "link": "https://www.cnbc.com/2026/08/24/why-all-the-fuss-about-bond-yields-is-happening-now.html",
      "description": "The textbooks say the cycle high in real yields should act as a restraint on economic growth and equity valuations.",
      "source": "CNBC",
      "image": "",
      "published": "2026-08-24T12:31:13+00:00",
      "published_display": "24.08 12:31",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Why this analyst predicts Circle stock could surge 75%",
      "link": "https://finance.yahoo.com/markets/stocks/article/why-this-analyst-predicts-circle-stock-could-surge-75-123017242.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/tMnSDL0RXwH.CC30J5Vw7Q--~B/aD00MjcyO3c9NjQwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-08/9bf7b814-d966-4ddb-aff2-94df908aba23",
      "published": "2026-08-24T12:30:17+00:00",
      "published_display": "24.08 12:30",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Sugar Prices Consolidate Recent Rally",
      "link": "https://www.nasdaq.com/articles/sugar-prices-consolidate-recent-rally",
      "description": "October NY world sugar #11 (SBV26 ) closed up +0.09 (+0.51%) on Friday, and October London ICE white sugar #5 (SWV26 ) closed down -0.60 (-0.11%). Sugar prices settled mixed on Friday, as prices consolidated recent sharp gains. Concerns…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-08-24T12:28:17+00:00",
      "published_display": "24.08 12:28",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Strategy raises $2 billion through MSTR sales and creates new USD Cash pool",
      "link": "https://www.coindesk.com/markets/2026/08/24/strategy-raises-usd2-billion-through-mstr-sales-and-creates-new-usd-cash-pool",
      "description": "The company sold 18.26 million MSTR shares, increased its USD Reserve to $5.1 billion and repurchased another $136.4 million of STRC.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/dd98498dbda09f933fbeac48aac3591d14c0deee-3018x1697.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-08-24T12:24:58+00:00",
      "published_display": "24.08 12:24",
      "sentiment": "positive",
      "tickers": [
        "MSTR"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Is Netflix (NFLX) Facing a Growth Slowdown After Its Strong First Quarter?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/netflix-nflx-facing-growth-slowdown-121811891.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/acfdf2ca74d0d955846a814c95b0a123.jpg",
      "published": "2026-08-24T12:18:11+00:00",
      "published_display": "24.08 12:18",
      "sentiment": "negative",
      "tickers": [
        "NFLX"
      ],
      "sectors": [
        "Media / Entertainment"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Temu owner’s shares rise as results beat estimates despite tumbling profits",
      "link": "https://www.marketwatch.com/story/temu-owners-shares-rise-as-results-beat-estimates-despite-tumbling-profits-18cf74ea?mod=mw_rss_topstories",
      "description": "PDD Holdings reported a 12% decline in net profits in the three months ended June 30, surpassing Wall Street consensus.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-01122000",
      "published": "2026-08-24T12:18:00+00:00",
      "published_display": "24.08 12:18",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    }
  ]
};
