// This file is auto-generated by fetch_news.py — do not edit by hand
const NEWS_DATA = {
  "generated_at": "2026-09-03T15:07:57.600264+00:00",
  "generated_at_display": "03.09.2026 15:07",
  "summary": {
    "total": 80,
    "signal_total": 70,
    "macro_total": 10,
    "positive": 31,
    "negative": 17,
    "neutral": 22,
    "top_tickers": [
      {
        "ticker": "NVDA",
        "count": 3
      },
      {
        "ticker": "AVGO",
        "count": 3
      },
      {
        "ticker": "SPY",
        "count": 2
      },
      {
        "ticker": "PYPL",
        "count": 2
      },
      {
        "ticker": "AMZN",
        "count": 2
      },
      {
        "ticker": "HON",
        "count": 2
      }
    ],
    "sectors": [
      "AI Infrastructure",
      "Automotive / EV",
      "Banking & Finance",
      "Big Tech",
      "Bonds / Macro",
      "Consumer Goods",
      "Cryptocurrencies",
      "Defense",
      "ETFs / Indices",
      "Healthcare",
      "Industrials",
      "Media / Entertainment",
      "Payments / Fintech",
      "Semiconductors",
      "Software / AI Analytics",
      "Software / Cloud"
    ],
    "source_counts": {
      "CNBC": 10,
      "CoinDesk": 3,
      "MarketWatch": 5,
      "Yahoo Finance": 37,
      "Nasdaq": 15,
      "Investing.com": 10
    }
  },
  "indices": [
    {
      "name": "S&P 500",
      "symbol": "^GSPC",
      "unit": "index",
      "price": 7721.8,
      "change_abs": -9.19,
      "change_pct": -0.12,
      "spark": [
        7665.73,
        7663.0801,
        7665.3501,
        7667.8198,
        7668.4502,
        7669.6201,
        7663.6699,
        7664.0898,
        7670.0601,
        7671.25,
        7669.7998,
        7667.4502,
        7714.1201,
        7711.25,
        7700.0698,
        7703.52,
        7697.54,
        7709.04,
        7720.9702,
        7721.7998
      ]
    },
    {
      "name": "Dow Jones",
      "symbol": "^DJI",
      "unit": "index",
      "price": 53552.11,
      "change_abs": -17.33,
      "change_pct": -0.03,
      "spark": [
        53003.25,
        52958.6016,
        52992.0508,
        53020.4219,
        53020.5898,
        53006.3594,
        52977.1211,
        53002.8711,
        53058.1602,
        53089.8711,
        53083.8281,
        53066.25,
        53511.0117,
        53491.4883,
        53336.9414,
        53343.0117,
        53398.9297,
        53493.8281,
        53542.6914,
        53552.1094
      ]
    },
    {
      "name": "Nasdaq Composite",
      "symbol": "^IXIC",
      "unit": "index",
      "price": 26479.97,
      "change_abs": -61.38,
      "change_pct": -0.23,
      "spark": [
        26196.0664,
        26192.7461,
        26194.8789,
        26202.5547,
        26197.8066,
        26209.7285,
        26188.4785,
        26190.0605,
        26215.8613,
        26214.418,
        26208.7988,
        26214.5156,
        26440.9707,
        26427.5469,
        26419.623,
        26447.9062,
        26393.1738,
        26425.8145,
        26478.4668,
        26479.9648
      ]
    },
    {
      "name": "Russell 2000",
      "symbol": "^RUT",
      "unit": "index",
      "price": 2954.84,
      "change_abs": -59.5,
      "change_pct": -1.97,
      "spark": [
        2947.3601,
        2949.9653,
        2947.5229,
        2948.8953,
        2952.2314,
        2953.5566,
        2954.801,
        2955.3101,
        2956.5208,
        2959.1765,
        2956.5447,
        2957.2117,
        2953.6675,
        2966.4006,
        2963.4414,
        2955.1055,
        2952.9424,
        2953.5071,
        2954.9421,
        2954.8423
      ]
    },
    {
      "name": "FTSE 100 (UK)",
      "symbol": "^FTSE",
      "unit": "index",
      "price": 10820.19,
      "change_abs": -57.91,
      "change_pct": -0.53,
      "spark": [
        10756.9102,
        10772.0498,
        10780.04,
        10786.6504,
        10799.5195,
        10813.2002,
        10803.9404,
        10810.25,
        10820.6396,
        10830.9004,
        10841.0703,
        10851.0,
        10861.96,
        10827.2002,
        10843.4102,
        10828.6904,
        10810.96,
        10817.7598,
        10818.6299,
        10820.1904
      ]
    },
    {
      "name": "DAX (Germany)",
      "symbol": "^GDAXI",
      "unit": "index",
      "price": 25937.96,
      "change_abs": -429.28,
      "change_pct": -1.63,
      "spark": [
        25795.0898,
        25822.2109,
        25815.9004,
        25855.9902,
        25851.7793,
        25862.8398,
        25836.4805,
        25841.7402,
        25868.5801,
        25908.2207,
        25951.4297,
        25971.7891,
        25996.5703,
        25980.3809,
        25994.9102,
        25927.9492,
        25927.3691,
        25931.7793,
        25942.8008,
        25937.9609
      ]
    },
    {
      "name": "Euro Stoxx 50",
      "symbol": "^STOXX50E",
      "unit": "index",
      "price": 6365.84,
      "change_abs": -119.83,
      "change_pct": -1.85,
      "spark": [
        6342.6099,
        6350.2598,
        6350.3101,
        6356.1401,
        6357.46,
        6357.3799,
        6349.73,
        6348.8701,
        6353.9502,
        6359.8198,
        6372.1099,
        6376.4302,
        6376.4302,
        6367.4302,
        6374.21,
        6359.1602,
        6360.2998,
        6365.8501,
        6366.6001,
        6365.8398
      ]
    },
    {
      "name": "Nikkei 225 (Japan)",
      "symbol": "^N225",
      "unit": "index",
      "price": 64214.48,
      "change_abs": -2191.08,
      "change_pct": -3.3,
      "spark": [
        64418.1484,
        64350.8203,
        64328.1992,
        64315.6406,
        64417.6797,
        64447.8203,
        64455.8281,
        64567.0781,
        64557.9297,
        64555.7812,
        64473.3398,
        64453.1914,
        64431.6797,
        64190.0898,
        63981.8398,
        64145.2812,
        64266.8906,
        64270.1016,
        64269.4805,
        64214.4805
      ]
    },
    {
      "name": "Hang Seng (Hong Kong)",
      "symbol": "^HSI",
      "unit": "index",
      "price": 25213.31,
      "change_abs": -352.43,
      "change_pct": -1.38,
      "spark": [
        25401.0508,
        25376.6602,
        25373.3809,
        25342.6699,
        25318.0898,
        25317.5898,
        25317.4902,
        25278.9102,
        25197.1699,
        25215.0703,
        25247.9492,
        25245.6309,
        25264.7695,
        25211.6699,
        25227.6699,
        25180.8594,
        25186.0195,
        25185.7402,
        25168.6504,
        25213.3105
      ]
    },
    {
      "name": "Gold (futures)",
      "symbol": "GC=F",
      "unit": "index",
      "price": 4527.7,
      "change_abs": 96.6,
      "change_pct": 2.18,
      "spark": [
        4468.7002,
        4472.0,
        4473.2002,
        4478.6001,
        4480.3999,
        4484.5,
        4490.2002,
        4490.3999,
        4493.2998,
        4514.7002,
        4540.8999,
        4532.8999,
        4527.6001,
        4517.2002,
        4517.1001,
        4515.7002,
        4523.6001,
        4519.2998,
        4527.2998,
        4527.7002
      ]
    },
    {
      "name": "WTI Crude Oil (futures)",
      "symbol": "CL=F",
      "unit": "index",
      "price": 92.15,
      "change_abs": 6.39,
      "change_pct": 7.45,
      "spark": [
        92.65,
        92.91,
        92.86,
        92.31,
        92.49,
        92.92,
        93.02,
        92.42,
        92.08,
        92.47,
        91.8,
        91.69,
        91.65,
        91.94,
        91.79,
        91.99,
        92.18,
        92.1,
        92.14,
        92.15
      ]
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC-USD",
      "unit": "index",
      "price": 80689.15,
      "change_abs": 3021.58,
      "change_pct": 3.89,
      "spark": [
        77476.5078,
        77708.6094,
        77789.2422,
        77894.7109,
        77890.0,
        77910.2734,
        78049.3516,
        77935.9375,
        78288.9531,
        78621.2891,
        78525.6719,
        78466.9297,
        78890.7109,
        78815.7422,
        78977.0625,
        79658.0,
        79745.4609,
        80550.0078,
        80734.8594,
        80689.1484
      ]
    },
    {
      "name": "10-Year US Treasury Yield",
      "symbol": "^TNX",
      "unit": "yield_pct",
      "price": 0.48,
      "change_abs": 0.0,
      "change_pct": 0.72,
      "spark": [
        0.4796,
        0.4792,
        0.4788,
        0.4792,
        0.4792,
        0.4792,
        0.4796,
        0.4796,
        0.4766,
        0.4744,
        0.4746,
        0.4744,
        0.4748,
        0.4754,
        0.4756,
        0.4756,
        0.476,
        0.4758,
        0.4754,
        0.4754
      ]
    },
    {
      "name": "VIX (Fear Index)",
      "symbol": "^VIX",
      "unit": "index",
      "price": 14.94,
      "change_abs": 0.51,
      "change_pct": 3.53,
      "spark": [
        15.42,
        15.39,
        15.41,
        15.27,
        15.26,
        15.34,
        15.4,
        15.37,
        15.3,
        15.14,
        15.03,
        15.01,
        15.02,
        14.98,
        15.03,
        14.94,
        14.92,
        14.97,
        14.96,
        14.94
      ]
    }
  ],
  "items": [
    {
      "title": "Dow rises 400 points as Treasury yields fall on lower Fed rate hike expectations: Live updates",
      "link": "https://www.cnbc.com/2026/09/02/stock-market-today-live-updates.html",
      "description": "Investors grew hopeful that the Federal Reserve may leave interest rates unchanged this month.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T15:04:47+00:00",
      "published_display": "03.09 15:04",
      "sentiment": "positive",
      "tickers": [
        "UST10Y",
        "FED"
      ],
      "sectors": [
        "Bonds / Macro"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Leon Black sues House Oversight over Epstein probe subpoenas, won't appear Thursday",
      "link": "https://www.cnbc.com/2026/09/03/leon-black-sues-house-oversight-epstein-probe-subpoenas.html",
      "description": "Black's attorneys say the NDAs being sought by the panel have nothing to do with his dealings with notorious sex offender Jeffrey Epstein.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T15:04:33+00:00",
      "published_display": "03.09 15:04",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Crypto for Advisors: Why crypto earnings reports can be misleading",
      "link": "https://www.coindesk.com/coindesk-indices/2026/09/03/crypto-for-advisors-why-crypto-earnings-reports-can-be-misleading",
      "description": "",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/5827e3d1483c884ef042b120e1127826773ce73a-4397x2850.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-03T15:00:00+00:00",
      "published_display": "03.09 15:00",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "How to invest in a booming stock market that’s way cheaper than the S&P 500",
      "link": "https://www.marketwatch.com/story/how-to-invest-in-a-booming-stock-market-thats-way-cheaper-than-the-s-p-500-b2f5ef5d?mod=mw_rss_topstories",
      "description": "Poland’s reclassification as a developed economy from an emerging market opens it up for investment by many more investors.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-36862352",
      "published": "2026-09-03T14:57:00+00:00",
      "published_display": "03.09 14:57",
      "sentiment": "positive",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Mastercard (MA) Stays Resilient with AI Integration and Payment Duopoly",
      "link": "https://finance.yahoo.com/markets/stocks/articles/mastercard-ma-stays-resilient-ai-145603430.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/530a7bf657cbd9a7ff21f554ae6ab731.jpg",
      "published": "2026-09-03T14:56:03+00:00",
      "published_display": "03.09 14:56",
      "sentiment": "positive",
      "tickers": [
        "MA"
      ],
      "sectors": [
        "Payments / Fintech"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Flywire (FLYW) Bets On Open Banking To Widen Its Payment Moat",
      "link": "https://finance.yahoo.com/markets/stocks/articles/flywire-flyw-bets-open-banking-145555831.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/0b82cc863a462e61f664075dd20f3b92.jpg",
      "published": "2026-09-03T14:55:55+00:00",
      "published_display": "03.09 14:55",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Danaher (DHR) Seen Deftly Navigating AI Integration",
      "link": "https://finance.yahoo.com/markets/stocks/articles/danaher-dhr-seen-deftly-navigating-145442960.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/4de858d44070a1d168359ecccfcc604b.jpg",
      "published": "2026-09-03T14:54:42+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Noteworthy ETF Inflows: AVLV, COST, MS, PGR",
      "link": "https://www.nasdaq.com/articles/noteworthy-etf-inflows-avlv-cost-ms-pgr",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the Avantis U.S. Large Cap Value ETF (Symbol: AVLV) where we have detected an approximate $517.7 million…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:17+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "neutral",
      "tickers": [
        "COST"
      ],
      "sectors": [
        "Consumer Goods"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "JEPI, MA, EOG, MDLZ: Large Inflows Detected at ETF",
      "link": "https://www.nasdaq.com/articles/jepi-ma-eog-mdlz-large-inflows-detected-etf",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the JPMorgan Equity Premium Income ETF (Symbol: JEPI) where we have detected an approximate $274.5 million…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:15+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "neutral",
      "tickers": [
        "JPM"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Noteworthy ETF Inflows: IUSB",
      "link": "https://www.nasdaq.com/articles/noteworthy-etf-inflows-iusb",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the iShares Core Universal USD Bond ETF (Symbol: IUSB) where we have detected an approximate $203.3 million…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:10+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dimensional US Large Cap Value ETF Experiences Big Outflow",
      "link": "https://www.nasdaq.com/articles/dimensional-us-large-cap-value-etf-experiences-big-outflow",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the Dimensional US Large Cap Value ETF (Symbol: DFLV) where we have detected an approximate $117.4 million…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:08+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "FIVA: ETF Outflow Alert",
      "link": "https://www.nasdaq.com/articles/fiva-etf-outflow-alert",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the Fidelity International Value Factor ETF (Symbol: FIVA) where we have detected an approximate $123.4…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:04+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Noteworthy ETF Outflows: FVAL, CTSH, HPQ, ZM",
      "link": "https://www.nasdaq.com/articles/noteworthy-etf-outflows-fval-ctsh-hpq-zm",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the Fidelity Value Factor ETF (Symbol: FVAL) where we have detected an approximate $190.4 million dollar…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:02+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "negative",
      "tickers": [
        "HPQ"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "First Trust Nasdaq Cybersecurity ETF Experiences Big Inflow",
      "link": "https://www.nasdaq.com/articles/first-trust-nasdaq-cybersecurity-etf-experiences-big-inflow",
      "description": "Looking today at week-over-week shares outstanding changes among the universe of ETFs covered at ETF Channel, one standout is the First Trust Nasdaq Cybersecurity ETF (Symbol: CIBR) where we have detected an approximate $187.1 million…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:54:01+00:00",
      "published_display": "03.09 14:54",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "PayPal cuts around 220 jobs in India as it aims to simplify global operations",
      "link": "https://www.investing.com/news/stock-market-news/paypal-cuts-around-220-jobs-in-india-as-it-aims-to-simplify-global-operations-4888189",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXMPEDAF0YT_M.jpg",
      "published": "2026-09-03T14:53:49",
      "published_display": "03.09 14:53",
      "sentiment": "negative",
      "tickers": [
        "PYPL"
      ],
      "sectors": [
        "Payments / Fintech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Congressman Ro Khanna Was Buying This Small-Cap Stock. Should You?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/congressman-ro-khanna-buying-small-145151706.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/688597b7e81e1295b515a6b18098435f.jpg",
      "published": "2026-09-03T14:51:51+00:00",
      "published_display": "03.09 14:51",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why is Energizer stock sliding today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-energizer-stock-sliding-today-93CH-4888231",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEB6U08A_M.jpg",
      "published": "2026-09-03T14:51:51",
      "published_display": "03.09 14:51",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "A memecoin making app becomes crypto’s top fee generators as Robinhood Chain activity explodes",
      "link": "https://www.coindesk.com/tech/2026/09/03/a-memecoin-making-app-becomes-crypto-s-top-fee-generators-as-robinhood-chain-activity-explodes",
      "description": "Users paid nearly $6 million in a day to create and trade tokens through Pons, more than they paid to use Pump or Hyperliquid, and even more than they paid to use Robinhood Chain itself.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/800c636f7f1593410f22ed849c8620a1f9d1cfd0-6000x4000.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-03T14:51:39+00:00",
      "published_display": "03.09 14:51",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "S&P Global (SPGI) Could Deliver Mid-Teens EPS Growth From a Cheaper Valuation",
      "link": "https://finance.yahoo.com/markets/stocks/articles/p-global-spgi-could-deliver-145100299.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/217ff6d90e3bf37f9f719211a5254dbb.jpg",
      "published": "2026-09-03T14:51:00+00:00",
      "published_display": "03.09 14:51",
      "sentiment": "positive",
      "tickers": [
        "SPGI"
      ],
      "sectors": [
        "Banking & Finance"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Is UnitedHealth Group (UNH) Finally Turning the Corner Under Stephen Hemsley?",
      "link": "https://finance.yahoo.com/healthcare/articles/unitedhealth-group-unh-finally-turning-145043391.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/c740e54fe5f56f1da027ee400791c870.jpg",
      "published": "2026-09-03T14:50:43+00:00",
      "published_display": "03.09 14:50",
      "sentiment": "neutral",
      "tickers": [
        "UNH"
      ],
      "sectors": [
        "Healthcare"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Netflix’s Acquisition Wishlist: Which Streaming Target Has the Best Odds?",
      "link": "https://finance.yahoo.com/media-advertising/articles/netflix-acquisition-wishlist-streaming-target-145040058.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/aff2c8cb373d75ddaf1a1c1e0bc6da25.jpg",
      "published": "2026-09-03T14:50:40+00:00",
      "published_display": "03.09 14:50",
      "sentiment": "neutral",
      "tickers": [
        "TGT",
        "NFLX"
      ],
      "sectors": [
        "Consumer Goods",
        "Media / Entertainment"
      ],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Wall Street Loves NuScale Power. Here's the Risk Analysts Are Glossing Over.",
      "link": "https://finance.yahoo.com/energy/articles/wall-street-loves-nuscale-power-145000761.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/c2a6c46e4cc7341d1e622ccf92187fc9.jpg",
      "published": "2026-09-03T14:50:00+00:00",
      "published_display": "03.09 14:50",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Netherlands Moves Gold From New York to London, Citing Geopolitical Unrest",
      "link": "https://finance.yahoo.com/markets/commodities/articles/netherlands-moves-gold-york-london-114300354.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/the_wall_street_journal_hosted_996/cf6b391d054ee377a8ecccfca184b4a0.jpg",
      "published": "2026-09-03T14:50:00+00:00",
      "published_display": "03.09 14:50",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 50.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Accrual to acquire Puzzle’s accounting firm business and software",
      "link": "https://finance.yahoo.com/small-business/articles/accrual-acquire-puzzle-accounting-firm-144929376.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/international_accounting_bulletin_542/fbe81eb42d46b03a86565891b55ff3db.jpg",
      "published": "2026-09-03T14:49:29+00:00",
      "published_display": "03.09 14:49",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Japanese Yen Extends Gains Versus Weaker U.S. Dollar",
      "link": "https://www.wsj.com/finance/currencies/yen-consolidates-may-be-supported-by-lingering-risks-of-fx-intervention-45c3cccb?siteid=yhoof2&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/wsj.com/7b2c285183be07ca3c4e8242b25a59a8.png",
      "published": "2026-09-03T14:48:00+00:00",
      "published_display": "03.09 14:48",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Social Security: See what's really changing in 2027",
      "link": "https://finance.yahoo.com/personal-finance/investing/article/social-security-see-whats-really-changing-in-2027-144723278.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/hC8175Gi2vaH9xkMcla_Mg--~B/aD0zMzc1O3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/cc114390-ecfa-4a7b-9357-fef7f74e7cbb_bae46b39c8d9201a045f23d306112ac0d44ba65bbd5de2555ffdc124c87f5f9f.jpg",
      "published": "2026-09-03T14:47:23+00:00",
      "published_display": "03.09 14:47",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Oddity Tech options flow signals defensive positioning ahead of September earnings",
      "link": "https://www.investing.com/news/stock-market-news/oddity-tech-options-flow-signals-defensive-positioning-ahead-of-september-earnings-93CH-4888226",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC0L0PD_M.jpg",
      "published": "2026-09-03T14:46:28",
      "published_display": "03.09 14:46",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "This Fund Bought Moderna Before It Nearly Tripled. See Its 2 New Stock Picks",
      "link": "https://finance.yahoo.com/markets/stocks/articles/fund-bought-moderna-nearly-tripled-144452535.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/a46da9068c58072daab2f794893d76d8.jpg",
      "published": "2026-09-03T14:44:52+00:00",
      "published_display": "03.09 14:44",
      "sentiment": "positive",
      "tickers": [
        "MRNA"
      ],
      "sectors": [
        "Healthcare"
      ],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "The U.S. economy powers up as summer winds down, but it’s not free of trip wires",
      "link": "https://www.marketwatch.com/story/the-u-s-economy-powers-up-as-summer-winds-down-but-its-not-free-of-tripwires-2208ae5a?mod=mw_rss_topstories",
      "description": "The largest part of the economy grew in August at the fastest pace in six months despite higher inflation and a new round of White House tariffs, suggesting the six-year-old U.S. expansion has plenty more room to run.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-94478098",
      "published": "2026-09-03T14:44:00+00:00",
      "published_display": "03.09 14:44",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 60.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Bitget in talks with Wall Street giants including BlackRock to fuel Asian distribution",
      "link": "https://www.coindesk.com/business/2026/09/03/bitget-in-talks-with-wall-street-giants-including-blackrock-for-asian-distribution",
      "description": "Gracy Chen highlighted the world's largest asset manager as one example of such a firm seeking to expand distribution of their tokenized ETFs in the region.",
      "source": "CoinDesk",
      "image": "https://cdn.sanity.io/images/s3y3vcno/production/b211dc0a2c42f8c64487bc73e191e498111d9fed-7737x5161.jpg?fm=jpg&w=1920&h=1080&crop=focalpoint&fit=clip",
      "published": "2026-09-03T14:41:25+00:00",
      "published_display": "03.09 14:41",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 45.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dell Just Jumped 16% and One Strategist Says That Is the Whole Tech Argument Right Now",
      "link": "https://finance.yahoo.com/markets/stocks/articles/dell-just-jumped-16-one-144032856.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/448f4389c07e6f60d5ab32a4f2ee73cc",
      "published": "2026-09-03T14:40:32+00:00",
      "published_display": "03.09 14:40",
      "sentiment": "positive",
      "tickers": [
        "DELL"
      ],
      "sectors": [
        "AI Infrastructure"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Campbell’s Cuts 13% of Workforce in Effort to Turn Around Struggling Operations",
      "link": "https://www.wsj.com/business/earnings/campbells-looks-to-reset-after-quarterly-loss-60335f2c?siteid=yhoof2&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/wsj.com/062a75a79ff42d444b90b58486aa4c13.jpg",
      "published": "2026-09-03T14:40:00+00:00",
      "published_display": "03.09 14:40",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Billionaires Like These 2 AI Data Center Stocks",
      "link": "https://finance.yahoo.com/technology/ai/articles/billionaires-2-ai-data-center-143957217.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/6bb1d8eb85b54c6b741ba52e7feefdcd.jpg",
      "published": "2026-09-03T14:39:57+00:00",
      "published_display": "03.09 14:39",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hugging Face approached Nvidia’s Huang weeks ahead of $12.9B acquisition, CEO tells CNBC",
      "link": "https://www.cnbc.com/2026/09/03/nvidia-agrees-to-buy-hugging-face-for-almost-13-billion-ai-expansion.html",
      "description": "Nvidia CEO Jensen Huang said that with Hugging Face, the chipmaker will \"expand access to AI for developers and institutions worldwide.\"",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T14:38:25+00:00",
      "published_display": "03.09 14:38",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "For 4 Years, The Villages’ Top Health Provider Allegedly Filed False Medicare Codes. The Bill Just Came Due: $541.5 Million.",
      "link": "https://finance.yahoo.com/healthcare/articles/4-years-villages-top-health-143807320.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/24_7_wall_st__718/9f498fbd3b7f66836e469db22c5d4244",
      "published": "2026-09-03T14:38:07+00:00",
      "published_display": "03.09 14:38",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Palantir, Robinhood among market cap stock movers on Thursday",
      "link": "https://www.investing.com/news/stock-market-news/palantir-robinhood-among-market-cap-stock-movers-on-thursday-93CH-4888213",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/AppliedMaterials_800x533_L_1645098425.jpg",
      "published": "2026-09-03T14:35:18",
      "published_display": "03.09 14:35",
      "sentiment": "neutral",
      "tickers": [
        "PLTR"
      ],
      "sectors": [
        "Software / AI Analytics"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Insider Waves Goodbye to Nearly 6,000 Shares of Energy Stock",
      "link": "https://finance.yahoo.com/markets/stocks/articles/insider-waves-goodbye-nearly-6-143501132.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/motleyfool.com/5a440778ac8f2b72736c872664e8a572.png",
      "published": "2026-09-03T14:35:01+00:00",
      "published_display": "03.09 14:35",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Can Better Star Ratings and Margin Expansion Drive Humana (HUM) Higher?",
      "link": "https://finance.yahoo.com/markets/stocks/articles/better-star-ratings-margin-expansion-143427291.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/97e8ea8c8d371122ca156b0564610927.jpg",
      "published": "2026-09-03T14:34:27+00:00",
      "published_display": "03.09 14:34",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Iran strikes Kuwait as Trump says renewed Mideast hostilities will not last 'too long'",
      "link": "https://www.cnbc.com/2026/09/03/us-iran-war-trump-hormuz-israel-middle-east-europe-kuwait.html",
      "description": "On Thursday, Kuwait's army said it was confronting hostile missile and drone attacks from Iran.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T14:32:47+00:00",
      "published_display": "03.09 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 55.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "General Motors leads U.S. automakers on near-term technical setup",
      "link": "https://www.investing.com/news/stock-market-news/general-motors-leads-us-automakers-on-nearterm-technical-setup-93CH-4888208",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEM2O07Q_1200_L.jpg",
      "published": "2026-09-03T14:32:24",
      "published_display": "03.09 14:32",
      "sentiment": "positive",
      "tickers": [
        "GM"
      ],
      "sectors": [
        "Automotive / EV"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Victoria’s Secret sees strong ‘bras and Pink’ sales, but not enough to satisfy investors",
      "link": "https://www.marketwatch.com/story/victorias-secret-sees-strong-bras-and-pink-sales-but-not-enough-to-satisfy-investors-48bfe36c?mod=mw_rss_topstories",
      "description": "The company delivered sales near the high end of its forecasted range, but Wall Street was expecting more, and the stock is headed for its worst day in more than a year.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-87805533",
      "published": "2026-09-03T14:32:00+00:00",
      "published_display": "03.09 14:32",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Amazon.com (AMZN): AI Exposure Adds, But Other Businesses Drive Results",
      "link": "https://finance.yahoo.com/markets/stocks/articles/amazon-com-amzn-ai-exposure-143009087.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/96b2a95f603866c28e00574448cae026.jpg",
      "published": "2026-09-03T14:30:09+00:00",
      "published_display": "03.09 14:30",
      "sentiment": "positive",
      "tickers": [
        "AMZN"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Think you maxed out your 401(k)? The real limit is actually almost $50,000 higher.",
      "link": "https://www.marketwatch.com/story/think-you-maxed-out-your-401-k-the-real-limit-is-actually-almost-50-000-higher-217a89ee?mod=mw_rss_topstories",
      "description": "You can unlock greater retirement wealth by reading this document that nearly everyone ignores.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-30294956",
      "published": "2026-09-03T14:30:00+00:00",
      "published_display": "03.09 14:30",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Why is Bullish stock rallying today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-bullish-stock-rallying-today-93CH-4888188",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/SP500StandardandPoors500Index_800x533_L_1657544297.jpg",
      "published": "2026-09-03T14:29:38",
      "published_display": "03.09 14:29",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why is BRP stock sliding today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-brp-stock-sliding-today-93CH-4888186",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC3B0CQ_M.jpg",
      "published": "2026-09-03T14:29:22",
      "published_display": "03.09 14:29",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why is Albemarle stock sliding today?",
      "link": "https://www.investing.com/news/stock-market-news/why-is-albemarle-stock-sliding-today-93CH-4888185",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC0Q1B5_M.jpg",
      "published": "2026-09-03T14:29:10",
      "published_display": "03.09 14:29",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Boeing technical analysis: the sell signal and key levels to watch",
      "link": "https://www.investing.com/news/stock-market-news/boeing-technical-analysis-the-sell-signal-and-key-levels-to-watch-93CH-4888170",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/moved_LYNXMPEM4D18E_L.jpg",
      "published": "2026-09-03T14:27:34",
      "published_display": "03.09 14:27",
      "sentiment": "negative",
      "tickers": [
        "BA"
      ],
      "sectors": [
        "Defense"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Ciena Earnings Beat. Why This AI Data Center Play Is Falling.",
      "link": "https://www.investors.com/news/technology/ciena-stock-cien-ciena-earnings-news-july26/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/179ce26d1e5b08e4e216b8dcaed74cd8.jpg",
      "published": "2026-09-03T14:26:37+00:00",
      "published_display": "03.09 14:26",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nasdaq 100 Movers: AVGO, HONIV",
      "link": "https://www.nasdaq.com/articles/nasdaq-100-movers-avgo-honiv",
      "description": "In early trading on Thursday, shares of Honeywell International topped the list of the day's best performing components of the Nasdaq 100 index, trading up 7.5%. Year to date, Honeywell International registers a 42.2% gain. And the…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:25:18+00:00",
      "published_display": "03.09 14:25",
      "sentiment": "positive",
      "tickers": [
        "AVGO",
        "HON",
        "QQQ"
      ],
      "sectors": [
        "ETFs / Indices",
        "Industrials",
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "S&P 500 Movers: APH, HOOD",
      "link": "https://www.nasdaq.com/articles/sp-500-movers-aph-hood",
      "description": "In early trading on Thursday, shares of Robinhood Markets topped the list of the day's best performing components of the S&P 500 index, trading up 11.9%. Year to date, Robinhood Markets registers a 5.9% gain. And the worst performing…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:25:02+00:00",
      "published_display": "03.09 14:25",
      "sentiment": "positive",
      "tickers": [
        "SPY"
      ],
      "sectors": [
        "ETFs / Indices"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Longsys prices Hong Kong listing at HK$236 per share - Bloomberg",
      "link": "https://www.investing.com/news/stock-market-news/longsys-prices-hong-kong-listing-at-hk236-per-share--bloomberg-93CH-4888154",
      "description": "",
      "source": "Investing.com",
      "image": "https://content-media.investing.com/news/LYNXNPEC0E0NG_M.jpg",
      "published": "2026-09-03T14:23:19",
      "published_display": "03.09 14:23",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Dow Movers: CAT, HONIV",
      "link": "https://www.nasdaq.com/articles/dow-movers-cat-honiv-4",
      "description": "In early trading on Thursday, shares of Honeywell International topped the list of the day's best performing Dow Jones Industrial Average components, trading up 7.5%. Year to date, Honeywell International Dis registers a 42.2% gain. And…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:22:31+00:00",
      "published_display": "03.09 14:22",
      "sentiment": "positive",
      "tickers": [
        "CAT",
        "HON",
        "DJI"
      ],
      "sectors": [
        "ETFs / Indices",
        "Industrials"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Texas Instruments Incorporated (TXN) Benefits from AI without Being Pure Play AI",
      "link": "https://finance.yahoo.com/markets/stocks/articles/texas-instruments-incorporated-txn-benefits-142036141.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/318214b27e0dfe70cf048105ca9e5501.jpg",
      "published": "2026-09-03T14:20:36+00:00",
      "published_display": "03.09 14:20",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cash Dividend On The Way From First Merchants (FRME)",
      "link": "https://www.nasdaq.com/articles/cash-dividend-way-first-merchants-frme",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 9/4/26, First Merchants Corp (Symbol: FRME) will trade ex-dividend, for its quarterly dividend of $0.37, payable on 9/18/26. As a percentage of FRME's recent stock price…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:19:22+00:00",
      "published_display": "03.09 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "STE Ex-Dividend Reminder - 9/4/26",
      "link": "https://www.nasdaq.com/articles/ste-ex-dividend-reminder-9-4-26",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 9/4/26, STERIS plc (Symbol: STE) will trade ex-dividend, for its quarterly dividend of $0.69, payable on 9/25/26. As a percentage of STE's recent stock price of $231.59,…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:19:17+00:00",
      "published_display": "03.09 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "AAON About To Put More Money In Your Pocket (AAON)",
      "link": "https://www.nasdaq.com/articles/aaon-about-put-more-money-your-pocket-aaon",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 9/4/26, AAON, Inc. (Symbol: AAON) will trade ex-dividend, for its quarterly dividend of $0.10, payable on 9/25/26. As a percentage of AAON's recent stock price of…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:19:14+00:00",
      "published_display": "03.09 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Ex-Div Reminder for PayPal Holdings (PYPL)",
      "link": "https://www.nasdaq.com/articles/ex-div-reminder-paypal-holdings-pypl",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 9/4/26, PayPal Holdings Inc (Symbol: PYPL) will trade ex-dividend, for its quarterly dividend of $0.14, payable on 9/25/26. As a percentage of PYPL's recent stock price…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:19:08+00:00",
      "published_display": "03.09 14:19",
      "sentiment": "neutral",
      "tickers": [
        "PYPL"
      ],
      "sectors": [
        "Payments / Fintech"
      ],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Cash Dividend On The Way From C.H. Robinson Worldwide (CHRW)",
      "link": "https://www.nasdaq.com/articles/cash-dividend-way-ch-robinson-worldwide-chrw",
      "description": "Looking at the universe of stocks we cover at Dividend Channel, on 9/4/26, C.H. Robinson Worldwide, Inc. (Symbol: CHRW) will trade ex-dividend, for its quarterly dividend of $0.63, payable on 10/2/26. As a percentage of CHRW's recent…",
      "source": "Nasdaq",
      "image": "",
      "published": "2026-09-03T14:19:02+00:00",
      "published_display": "03.09 14:19",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 5.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Andvari Associates Strategic Investment in Martin Marietta Materials (MLM)",
      "link": "https://finance.yahoo.com/markets/stocks/articles/andvari-associates-strategic-investment-martin-141742133.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/bbfa7243a0f54e25e6c8ef61203751ce.jpg",
      "published": "2026-09-03T14:17:42+00:00",
      "published_display": "03.09 14:17",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Binance Founder ‘CZ’ Says Capital Is Returning To Crypto Market",
      "link": "https://finance.yahoo.com/markets/crypto/articles/binance-founder-cz-says-capital-141700689.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/cryptoprowl_304/477ba04756e3d0abde0b06842e6b57b7.jpg",
      "published": "2026-09-03T14:17:00+00:00",
      "published_display": "03.09 14:17",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Stock Market Today: Nasdaq Leads As Fed's Waller Signals This; Snowflake Soars (Live Coverage)",
      "link": "https://www.investors.com/market-trend/stock-market-today/dow-jones-sp500-nasdaq-treasury-yields-broadcom-stock-avgo/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/b93082b62d669a716dcee1724ff49dd4.jpg",
      "published": "2026-09-03T14:14:28+00:00",
      "published_display": "03.09 14:14",
      "sentiment": "neutral",
      "tickers": [
        "SNOW"
      ],
      "sectors": [
        "Software / Cloud"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Microsoft Corporation (MSFT) Generates Revenues and Profits Beyond AI Theme",
      "link": "https://finance.yahoo.com/markets/stocks/articles/microsoft-corporation-msft-generates-revenues-141420996.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/5ec329719e2363fbf46dd87eaacb07c7.jpg",
      "published": "2026-09-03T14:14:20+00:00",
      "published_display": "03.09 14:14",
      "sentiment": "positive",
      "tickers": [
        "MSFT"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Why HPE Stock Is Falling Amid Fiscal Q3 Earnings Beat",
      "link": "https://www.investors.com/news/technology/hpe-stock-hpe-earnings-news-july26/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/540b79c8b5e63f10ff4289393a5b6938.jpg",
      "published": "2026-09-03T14:11:32+00:00",
      "published_display": "03.09 14:11",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Nvidia confirms $13 billion acquisition of open-weight AI platform Hugging Face",
      "link": "https://finance.yahoo.com/markets/article/nvidia-confirms-13-billion-acquisition-of-open-weight-ai-platform-hugging-face-141058641.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/RyA3AzHRJ7Qs4YRd9i0CjA--~B/aD0yNTY2O3c9NDU2MTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/f82dae40-4363-11ed-bffa-da11af28a41d_5207744486f6f2de26e0a02f4cab602257586ecdd6452a4c390b1570131546c7.jpg",
      "published": "2026-09-03T14:10:58+00:00",
      "published_display": "03.09 14:10",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 60.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Liquidia Corporation’s (LQDA) Yutrepia Launch Continues to Outpace the Expectations",
      "link": "https://finance.yahoo.com/healthcare/articles/liquidia-corporation-lqda-yutrepia-launch-141014617.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/82afea915a6d0fbab0d0cce2d3a7bf27.jpg",
      "published": "2026-09-03T14:10:14+00:00",
      "published_display": "03.09 14:10",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Fed Governor Waller indicates he will support holding rates steady at September meeting",
      "link": "https://www.cnbc.com/2026/09/03/fed-governor-waller-indicates-he-will-support-holding-rates-steady-at-september-meeting.html",
      "description": "In remarks that seem to contrast with statements last week from Chairman Kevin Warsh, Waller expressed confidence in the current inflation trends.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T14:06:52+00:00",
      "published_display": "03.09 14:06",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 30.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Whole Foods CEO bets on smaller stores and the latest Amazon tech to win over shoppers",
      "link": "https://finance.yahoo.com/markets/article/whole-foods-ceo-bets-on-smaller-stores-and-the-latest-amazon-tech-to-win-over-shoppers-140631065.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/oxYAVF4yyFatM5wlzYJ1rw--~B/aD0zMDAxO3c9NTMzNTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-09/6764c27f-b08e-442a-aed6-73805a960946",
      "published": "2026-09-03T14:06:31+00:00",
      "published_display": "03.09 14:06",
      "sentiment": "neutral",
      "tickers": [
        "AMZN"
      ],
      "sectors": [
        "Big Tech"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Sands Capital Select Growth Fund Sold DoorDash’s (DASH) in Q2",
      "link": "https://finance.yahoo.com/markets/stocks/articles/sands-capital-select-growth-fund-140621125.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/insidermonkey.com/df26539eb76a0455664e4924c7ceef05.jpg",
      "published": "2026-09-03T14:06:21+00:00",
      "published_display": "03.09 14:06",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Three Questions Every Utility Should Ask About Advanced Reactors",
      "link": "https://finance.yahoo.com/energy/articles/three-questions-every-utility-ask-140502949.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/power_magazine_984/4b4913c1e9d67141593c09c9491cb8a1.png",
      "published": "2026-09-03T14:05:02+00:00",
      "published_display": "03.09 14:05",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 10.0,
      "content_type": "macro_context",
      "llm_classified": true
    },
    {
      "title": "Stocks edge up as Nvidia leads tech higher following Hugging Face deal announcement: AlphaCheck",
      "link": "https://finance.yahoo.com/markets/article/stocks-edge-up-as-nvidia-leads-tech-higher-following-hugging-face-deal-announcement-alphacheck-140448366.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://s.yimg.com/uu/api/res/1.2/FFIgd_Dm7jstcscWa33Lfg--~B/aD01MjE4O3c9NzgyMzthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-09/e821502a-e4c3-446c-b486-f327cc236170",
      "published": "2026-09-03T14:04:48+00:00",
      "published_display": "03.09 14:04",
      "sentiment": "positive",
      "tickers": [
        "NVDA"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 40.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Ultragenyx's 'Fall From Grace' — Shares Crash 47%, Hitting A Record Low",
      "link": "https://www.investors.com/news/technology/ultragenyx-stock-angelman-syndrome-failure/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/703850409d67abc5aa561ec3cc7d1f01.jpg",
      "published": "2026-09-03T14:03:31+00:00",
      "published_display": "03.09 14:03",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 50.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Hidden China risks are emerging in America’s multibillion-dollar AI data center boom",
      "link": "https://www.cnbc.com/2026/09/03/us-ai-data-centers-china-supply-chain.html",
      "description": "U.S. AI data centers rely on China-linked supplies of transformers, batteries and optical gear as Washington moves to tighten restrictions on foreign equipment.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T14:00:49+00:00",
      "published_display": "03.09 14:00",
      "sentiment": "negative",
      "tickers": [],
      "sectors": [],
      "importance": 25.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Snowflake Earnings Beat. Why Snowflake's AI Product Strategy Is Jelling.",
      "link": "https://www.investors.com/news/technology/snowflake-stock-snow-snowflake-earnings-news-july26/?src=A00220&yptr=yahoo",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/ibd.com/0dee8ec9f7c97a7fc65e1d732445d5f4.jpg",
      "published": "2026-09-03T13:59:20+00:00",
      "published_display": "03.09 13:59",
      "sentiment": "positive",
      "tickers": [
        "SNOW",
        "MSTR"
      ],
      "sectors": [
        "Cryptocurrencies",
        "Software / Cloud"
      ],
      "importance": 35.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "This chipmaker that works with Google can gain ground, Macquarie Equity Research says",
      "link": "https://www.cnbc.com/2026/09/03/this-ai-chip-stock-can-gain-ground-macquarie-equity-research-says-.html",
      "description": "Broadcom could see a lot of upside, even as investors seem to express doubts over its business outside of its Google partnership, per Macquarie Equity Research.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T13:58:18+00:00",
      "published_display": "03.09 13:58",
      "sentiment": "positive",
      "tickers": [
        "AVGO",
        "GOOGL"
      ],
      "sectors": [
        "Big Tech",
        "Semiconductors"
      ],
      "importance": 20.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Bitcoin-Gold Correlation Hits Six-Year High",
      "link": "https://finance.yahoo.com/markets/crypto/articles/bitcoin-gold-correlation-hits-six-135500399.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/cryptoprowl_304/a3280a88bdde4558972db41b2675ca9e.jpg",
      "published": "2026-09-03T13:55:00+00:00",
      "published_display": "03.09 13:55",
      "sentiment": "neutral",
      "tickers": [
        "BTC"
      ],
      "sectors": [
        "Cryptocurrencies"
      ],
      "importance": 15.0,
      "content_type": "market_signal",
      "llm_classified": true
    },
    {
      "title": "Billionaire family offices back healthcare and biotech startups in August",
      "link": "https://www.cnbc.com/2026/09/03/family-offices-health-care-biotech-startups-august.html",
      "description": "The personal investment firms of titans like Stanley Druckenmiller are backing innovations in gene editing, drug discovery and more.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T13:54:50+00:00",
      "published_display": "03.09 13:54",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 11.7,
      "content_type": "market_signal",
      "llm_classified": false
    },
    {
      "title": "Average 401(k), IRA balances hit record highs — but more workers are raiding their accounts, Fidelity says",
      "link": "https://www.cnbc.com/2026/09/03/401k-ira-retirement-balances-leakage-fidelity.html",
      "description": "Retirement account balances rose in the second quarter amid market gains, according to Fidelity. At the same time, more savers tapped their accounts for cash.",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T13:54:17+00:00",
      "published_display": "03.09 13:54",
      "sentiment": "positive",
      "tickers": [],
      "sectors": [],
      "importance": 16.7,
      "content_type": "market_signal",
      "llm_classified": false
    },
    {
      "title": "Kraken Parent Company Payward Delays IPO",
      "link": "https://finance.yahoo.com/markets/crypto/articles/kraken-parent-company-payward-delays-135300700.html",
      "description": "",
      "source": "Yahoo Finance",
      "image": "https://media.zenfs.com/en/cryptoprowl_304/ac8022faf34227214db9079ea6343c56.jpg",
      "published": "2026-09-03T13:53:00+00:00",
      "published_display": "03.09 13:53",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 37.7,
      "content_type": "market_signal",
      "llm_classified": false
    },
    {
      "title": "As Broadcom’s stock falls, Wall Street focuses on the company’s forecast",
      "link": "https://www.marketwatch.com/story/broadcom-stock-fall-as-investors-weigh-guidance-heres-what-wall-street-analysts-are-saying-9048c0e6?mod=mw_rss_topstories",
      "description": "Broadcom perhaps came up short of true “market expectations” with its latest outlook, though one analyst said management may be taking a conservative stance on its potential.",
      "source": "MarketWatch",
      "image": "https://images.mktw.net/im-63990339",
      "published": "2026-09-03T13:46:00+00:00",
      "published_display": "03.09 13:46",
      "sentiment": "negative",
      "tickers": [
        "AVGO"
      ],
      "sectors": [
        "Semiconductors"
      ],
      "importance": 20.7,
      "content_type": "market_signal",
      "llm_classified": false
    },
    {
      "title": "Campbell's forecasts weak year ahead on pressured consumer spending",
      "link": "https://www.cnbc.com/2026/09/03/campbells-forecasts-weak-year-ahead-on-pressured-consumer-spending.html",
      "description": "\"Our results remain unacceptable,\" CEO Mick Beekhuizen said, adding that Campbell's will be \"addressing reality head-on.\"",
      "source": "CNBC",
      "image": "",
      "published": "2026-09-03T13:42:38+00:00",
      "published_display": "03.09 13:42",
      "sentiment": "neutral",
      "tickers": [],
      "sectors": [],
      "importance": 11.6,
      "content_type": "market_signal",
      "llm_classified": false
    }
  ]
};
